learningeconomy/LearnCard

.changeset/swift-crabs-confess.md
packages/learn-card-core/package.json
packages/learn-card-core/tsconfig.json
pnpm-lock.yaml
services/meta-mask-snap/snap.manifest.json

[WE-2549] Fix the AddImplicitLearnCardArgument error
Building types can do some weird things! Some of our types are broken when they're built, causing
third parties wanting to write plugins to have TS issues
Fixes the above by manually editing our built types after their made 🙃
- Explicitly adds a `types/wallet` alias, making the built types add in `import(".")` for those broken imports
- Adds an extra step to our build script that runs `sed` over the built script, removing those broken imports
- Adds `shx` as a dep. We were already using this, but now it's actually in our package.json 😳
I really wanted to do this without manually updating our built types, but it seems like there's no 
other way for now =(
Also, `shx` has a huge output for `sed` until they update that package. I tried to …

[WE-2549] Fix Built Types

---

.changeset/blue-buses-sit.md
packages/learn-card-types/src/vc.ts

For MV, we want to use an embedded context when issuing meta credentials
Loosens the context type in `@learncard/types` to allow embedded contexts
[This is spelled out in the spec](https://www.w3.org/TR/json-ld11/#the-context:~:text=Contexts%20can%20either%20be%20directly%20embedded%20into%20the%20document%20(an%20embedded%20context)%20or%20be%20referenced%20using%20a%20URL.)!
Updates type/validator from `string[]` to `(string | Record<string, any>)[]`;
None!
Pop open the CLI and run the following commands:
```js
let uvc = learnCard.invoke.getTestVc();
uvc['@context'].push({ Test: { ['@id']: 'nice', ['@type']: '@id' } });
await types.ContextValidator.spa(uvc['@context']);
```
If you see success, then the type is successfully loosened!

Allow Embedded Contexts

---

.changeset/shaggy-eggs-tap.md
packages/learn-card-core/src/wallet/plugins/idx/idx.ts
packages/learn-card-core/src/wallet/plugins/idx/types.ts

It is desirable to store things other than credentials in IDX. This PR allows consumers to do that!
Adds `getIDXIndex` and `setIDXIndex` methods to allow manually managing IDX
Open up the CLI and try the following:
```
const index = await learnCard.invoke.getIDXIndex();
index.nice = [];
await learnCard.invoke.setIDXIndex(index);
await learnCard.invoke.getIDXIndex(); // Should have nice inside of it!
await learnCard.index.all.get(); // Should still work correctly!
```

Allow Better Access to IDX

---

.changeset/plenty-bugs-clean.md
packages/learn-card-core/src/wallet/plugins/idx/types.ts

Putting custom fields in IDX index via `setIDXIndex` will currently be wiped when using a regular
index method with IDX such as `addCredential`. This is because the zod validator for `CredentialsList`
was wide enough to accept that shape, but was stripping the unknown keys.
Fixes the above bug
Added `catchall(z.any())` to the zod validator
None!
Add custom fields to your IDX index using `learnCard.invoke.setIDXIndex` in the CLI, then call
`learnCard.index.IDX.add({ id: '1', uri: 'lc:ceramic:23476890' })` and make sure your custom fields
persist!

Fix Wiping Index

---

.changeset/old-seahorses-applaud.md

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1vuk5eaQyiPIJ1riSYfPCmxdUmNUvNnA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=vUxCdny)

React Changeset

---

.changeset/fuzzy-glasses-flow.md
packages/react-learn-card/src/components/Notification/__tests__/Notification.test.tsx

fixes notification failing tests

fix notification tests

---

.changeset/stupid-fireants-fry.md
packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.stories.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCardCategoryType.tsx
packages/react-learn-card/src/components/VCDisplayCard2/index.ts
packages/react-learn-card/src/types/index.ts
services/meta-mask-snap/snap.manifest.json

Add additional optional prop to VCDisplayCard2 and fix VC type display

---

.changeset/tiny-zoos-return.md
.github/workflows/deploy.yml
.github/workflows/release.yml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18SCNR6zLDID4Cv3lltUtNJ7ZGdiOuUUvk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=aP-cmQV)

Add SEED to git flows

---

.changeset/proud-goats-remain.md
packages/learn-card-types/src/lcn.ts
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/helpers/connection.helpers.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/test/profiles.spec.ts
services/meta-mask-snap/snap.manifest.json

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1X1j2bjHvXswUv2nqJUCw4VKCRIBeTsA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hoaIgq6)
When searching for profiles, it's difficult to know if you are already connected or not. 
Add support for Connection Request status to `searchProfiles`.
- Adds `includeConnectionStatus` flag to searchProfiles in brain-service
- Adds `includeConnectionStatus` flag to searchProfiles LCN plugin
- Adds LCNProfileConnectionStatusEnum, with following values:
```
LCNProfileConnectionStatusEnum = z.enum([
'CONNECTED',
'PENDING_REQUEST_SENT',
'PENDING_REQUEST_RECEIVED',
'NOT_CONNECTED',
]);
```

Feat: Add connection status option to searchProfiles

---

.changeset/eight-planes-tease.md
.github/workflows/chromatic.yml
.github/workflows/deploy.yml
.github/workflows/manifest.yml
.github/workflows/release.yml
.github/workflows/test.yml

Update actions to use pnpm i no frozen lockfile

---

.changeset/swift-pots-hug.md
packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.stories.tsx
packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
pnpm-lock.yaml
services/meta-mask-snap/snap.manifest.json

Inner click wrapper was wrapping button as well, fixed so that it only wraps above section.
added tailwind mouse-cursor class to clickable regions.

fix: small boost card update

---

.github/workflows/deploy.yml
services/learn-card-network/brain-service/src/dids.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1W71HuPzAkg7tInudsIYZXxomX5TOuE8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tI4rGnn)

Fix: DID routes CORs

---

.github/workflows/deploy.yml
services/learn-card-network/brain-service/src/dids.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18N8bFZxbkX5azV9Tet7JQPyKVW7DvKlRo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HIpvQnc)

Fix: cors options

---

.changeset/poor-tips-leave.md
packages/learn-card-core/src/wallet/plugins/index.ts
packages/plugins/learn-card-network/src/learnCard.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18kSHlOMv2caOYbPT9cTrHRmihfek7fIw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2qYD2kW)

Fix: Verify Prettify

---

.changeset/sharp-llamas-rush.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
services/meta-mask-snap/snap.manifest.json

Add title override to VCDisplayCard 2

---

.changeset/coca-cola.md
pnpm-lock.yaml

Changeset test

---

.changeset/swift-camels-divide.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
pnpm-lock.yaml

Add showBackButton prop to vcdisplaycard2

---

.changeset/many-badgers-carry.md
packages/react-learn-card/src/components/Notification/__tests__/Notification.test.tsx
packages/react-learn-card/src/components/Notification/types.ts
packages/react-learn-card/src/components/svgs/ShieldChevron.tsx
packages/react-learn-card/src/components/svgs/index.ts

Updates the notification's social badge icon, so it uses the correct one
before:
after: 
- [C] Related to a Jira issue ([create one if not](https://welibrary.atlassian.net/jira/software/projects/WE/boards/2))
- [C] My code follows **style guidelines** (eslint / prettier)
- [C] I have **manually tested** common end-2-end cases

fix: update social badge icon

---

.changeset/late-melons-wait.md
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/brain-service/src/dids.ts
services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
services/meta-mask-snap/snap.manifest.json

CORS fails with User-Agent headers in firefox / safari / iOS environments. DID documents should be universally retrievable to prevent major errors.
Adds CORS response and header in YML, overriding defaults which did not allow CORS in safari and firefox.

Fix: CORS for did routes

---

.changeset/chilly-pumas-bathe.md
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/helpers/presentation.helpers.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19uL7sjRP9ETvB3KwKSJ0jP15UhTg5TJ0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=v2tRgGC)

Fix: Boost Notification

---

.changeset/cyan-falcons-decide.md
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/helpers/connection.helpers.ts
services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
services/learn-card-network/brain-service/src/helpers/presentation.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19hRtRG58KXSGqYHZJrzsA3fs4SzSf9g%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=zYnoM4a)
`sendBoost()` seems to be timing out occasionally, causing an error on the client. 
For example, here is a invocation that took 8s. While we should identify root cause of this long of function, this temporarily relieves that issue:
Additionally, some notifications weren't being sent when function finishes before async operations can complete, so this adds await statements to notification sending. 
This is a PR to add monitoring & extra memory/timeouts + logs to quantify issue.
- We should monitory why sendBoost() takes 5-11 …

Fix: Increase memory size & timeouts and adds logs for LCN sendBoost()

---

.changeset/tidy-laws-taste.md
packages/learn-card-types/src/lcn.ts
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/accesslayer/signing-authority/create.ts
services/learn-card-network/brain-service/src/accesslayer/signing-authority/delete.ts
services/learn-card-network/brain-service/src/accesslayer/signing-authority/read.ts
services/learn-card-network/brain-service/src/accesslayer/signing-authority/relationships/create.ts
services/learn-card-network/brain-service/src/accesslayer/signing-authority/relationships/read.ts
services/learn-card-network/brain-service/src/cache/claim-links.ts
services/learn-card-network/brain-service/src/cache/index.ts
services/learn-card-network/brain-service/src/dids.ts
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/helpers/learnCard.helpers.ts
services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
services/learn-card-network/brain-service/src/helpers/signingAuthority.helpers.ts
services/learn-card-network/brain-service/src/models/Profile.ts
services/learn-card-network/brain-service/src/models/SigningAuthority.ts
services/learn-card-network/brain-service/src/models/index.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/src/types/boost.ts
services/learn-card-network/brain-service/src/types/profile.ts
services/learn-card-network/brain-service/test/boosts.spec.ts
services/learn-card-network/brain-service/test/profiles.spec.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19ppqaPLzJAAGyNBa5pJS3OpItYQGnxb8Y%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=NObnSa0)
Add Signing Authorities and Claim Links
Adds the following plugin Methods to the LearnCard Network:
-   registerSigningAuthority: (endpoint: string, name: string, did: string) => Promise<boolean>;
-   getRegisteredSigningAuthorities: (endpoint: string, name: string, did: string) => Promise<LCNSigningAuthorityForUserType[]>;
-   getRegisteredSigningAuthority: (endpoint: string, name: string) => Promise<LCNSigningAuthorityForUserType>;
-   generateClaimLink: (boostUri: string, claimLinkSA: LCNBoostClaimLinkSigningAuthorityType, …

Add Signing Authorities and Claim Links

---

.changeset/few-trainers-buy.md
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
pnpm-lock.yaml

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX192731laO4qIlI99PsMV8fpcjDP26fvNrQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=RaN1Rcc)

Fix: Add Options to generateClaimLink

---

.changeset/pink-houses-tap.md
packages/react-learn-card/src/components/NotificationBoostCard/NotificationBoostCard.tsx
packages/react-learn-card/src/components/NotificationUserAcceptedBoostCard/NotificationUserAcceptedBoostCard.tsx
packages/react-learn-card/src/components/NotificationUserCard/NotificationUserCard.tsx
pnpm-lock.yaml

Did not export boost notification components properly.

fix: Export LCA notification card components properly

---

.changeset/chilly-pots-walk.md
services/learn-card-network/brain-service/src/accesslayer/boost/create.ts
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/helpers/connection.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/profiles.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1AZhxAkvrIVtFJ4gJ32ZA5SEFzhbGx4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=o3w4wlW)
Right now, when you register a signing authority, the cached did doc doesn't get deleted, which breaks important flows which rely downstream on the did doc being updated to use the signing authority.
This deletes the cached did doc when registering a SA

Fix: Delete DID doc after registering SA

---

.changeset/chatty-hotels-share.md
services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18wuv6uXmbttGxckrv6maTNO9PlYfpQhyI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_Q2QqSm)
Notifications lack timestamps right now.
This adds a timestamp to a notification payload before sending.

Fix: Add `sent` timestamp

---

.changeset/healthy-beers-mix.md
.changeset/light-pots-rescue.md
.eslintrc.js
packages/plugins/learn-card-network/src/plugin.ts
packages/react-learn-card/src/components/VCDisplayCard2/InfoBox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/IssueHistoryBox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/TruncateTextBox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VC2BackFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCardCategoryType.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VerificationRow.tsx
packages/react-learn-card/src/components/VCVerificationCheck/VCVerificationCheck.tsx

Just some small fixes I made while running through things
Fixes the bugs that came up in the design meeting today
- Add `select-none` in various places 
- `div` -> `button`
- Fix expiration text
- Fix bad issuanceDate
Link it with LCA then look at VCs!

Minor Polishes

---

.changeset/curvy-lamps-fold.md
.eslintrc.js
packages/learn-card-network/brain-client/src/index.ts
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

Right now, the only way to get boost metadata for a given boost URI is to call `getBoosts` and then
search through the results for a matching URI
Adds a `getBoost` route that takes in a boost URI and spits out the boost metadata
I chose not to deserialize the boost json because I'm not sure that we even want to include the boost
here, and I'm also not sure if that's always going to be an unsigned VC or if a signed VC is allowed
there too!
Open up the CLI, call `lc.invoke.getBoosts` to find a boost URI, then call `lc.invoke.getBoost` with that URI

Add getBoost route

---

.changeset/proud-cameras-knock.md
.changeset/slimy-lobsters-visit.md
.changeset/thin-shoes-mix.md
packages/learn-card-types/src/lcn.ts
packages/react-learn-card/src/components/VCDisplayCard2/VerificationRow.tsx
services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts

- :bug: Hide check if not passed in
- :bug: Don't send notifications for self-boosts
- :art: Don't allow to/from in notifications to be strings
Trying to get some quick polishes in for LCA!
- Hide check in VCDisplayCard2 if needed
- Don't send notifications for self-boosts
- Don't allow to/from in notification type to be strings

Small Polishes

---

.changeset/popular-timers-change.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

Just tiny things I want to fix
- Hide green verification check when verifications fail
- Make GenericBoostCard a button not a div

Small VCCard fixes

---

.changeset/lazy-rings-guess.md
.changeset/nine-carpets-knock.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/vc-templates/src/templates.ts

If you go the OBv3 spec right now, you'll see they've updated to a 3.0.1 context! (https://www.imsglobal.org/spec/ob/v3p0/#json-ld-context-file)
We need to add support for that!
Updates Didkit/SSI to resolve the v3.0.1 context, and uses it by default in `vc-templates`
- Adds OBv3 v3.0.1 to SSI/Didkit
- Updates the achievementt and boost credentials in `vc-templates` plugin to use OBv3 v3.0.1
None!
Pop open the CLI and run the following commands
```js
const uvc = learnCard.invoke.newCredential({ type: 'achievement' });
const vc = await learnCard.invoke.issueCredential(uvc);
await learnCard.invoke.verifyCredential(vc);
```
If there's no error, we're all good!

Add support for OBv3 v3.0.1 Context

---

.changeset/famous-shrimps-brake.md
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/accesslayer/profile/read.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/test/profiles.spec.ts

https://welibrary.atlassian.net/browse/WE-2684
https://welibrary.atlassian.net/browse/WE-2745
Let’s sort contacts list by first name first letter a-z.
Hide "Service Profiles" from search and Contacts.
Added additional param "includeServiceProfiles" that defaults to false
Adds a default sort

[WE-2684][WE-2745] Add optional includeServiceProfiles(default = false) to searchProfiles, default orderby displayName

---

.changeset/lazy-laws-cover.md
packages/react-learn-card/src/components/VCDisplayCard2/FitText.tsx

Sometimes, on desktop, in Metaversity, the TextFit thing doesn't work, and I'm not sure why.
Moved it to `useLayoutEffect` and added an extra fit call using `setTimeout` with a 0 timeout to manually refit after all layout is done
Link to MV, open MV, log in as demo account, look at Skills with long names

Fix Weird Text Issue in MV

---

pnpm-lock.yaml
services/learn-card-network/brain-service/src/cache/claim-links.ts
services/learn-card-network/brain-service/src/cache/index.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19UVno8RwHbQoUdepJQHfWGXGyWiMAVgE4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=nh7YcOX)
Several users have reported that, after generating a claim boost link, they send it out, and suddenly people start getting errors that the link is no longer valid.
When no TTL was specified, the TTL of the claim boost link was being set to 24 hours. This PR updates the cache to allow setting no TTL, and updates the generate claim boost link to set no TTL if none is specified instead of a default 24 hours.
- Update Cache to Allow 'false' in the TTL, and use .set instead of .setex
- Update generate claim boost link to set …

Fix: Claim Boost Link Expiring in 24 Hours

---

.changeset/beige-tigers-scream.md
.changeset/heavy-parents-invent.md
services/learn-card-network/brain-service/src/global.d.ts
services/learn-card-network/brain-service/src/routes/utilities.ts
services/learn-card-network/brain-service/tsconfig.build.json
services/learn-card-network/brain-service/tsconfig.json
services/learn-card-network/learn-cloud-service/src/global.d.ts
services/learn-card-network/learn-cloud-service/src/routes/utilities.ts
services/learn-card-network/learn-cloud-service/tsconfig.build.json

It can be hard to tell when a deploy goes through for the LCN services!
Adds the version from package.json into the text returned by the health check endpoint
Just imports package.json and spits out the version from there!
None! This is just a tiny handy thing =D
`pnpm start` inside each of the two LCN services and go to `localhost:3000/api/health-check` and make sure it shows the correct version!

Display version in Health Check

---

.changeset/happy-jars-drop.md
docs/package.json
packages/react-learn-card/package.json
pnpm-lock.yaml

Fixes an issue with tests failing on react-learn-card due to react & react-dom version incompatibilities
- confirmed tests are now working 
- confirmed local changes are working (storybook)
- confirmed local package linking is working as expected with learncardApp

bump react to v18

---

.changeset/soft-dodos-greet.md
.changeset/soft-grapes-travel.md
packages/react-learn-card/src/components/CircleIcon/CircleIcon.tsx
packages/react-learn-card/src/components/RoundedSquare/RoundedSquare.tsx

Adds a loading prop and display state for Rounded Square component used on LCA wallet page
https://github.com/learningeconomy/LearnCard/assets/18289875/4b3f7768-717f-4db5-a42e-177b2d7cd2f1

chore: Add loading spinner display and props to Rounded Square

---

.changeset/olive-crabs-fail.md
packages/react-learn-card/src/components/Lightbox/Lightbox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/MediaAttachmentsBox.tsx
pnpm-lock.yaml

- Adds a max width/height so lightboxed images are always smaller than the screen size, giving the user space to click outside the image
- Adds links to open the attachment in a new tab in document and link attachments
https://welibrary.atlassian.net/browse/WE-2805
https://welibrary.atlassian.net/browse/WE-2806
https://welibrary.atlassian.net/browse/WE-2807
View the media attachments of an existing boost
Make sure the changes work on any mobile devices

Various lightbox iterations

---

.changeset/bright-onions-relate.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.d.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/didkit/src/didkit/pkg/didkit_wasm_bg.wasm.d.ts

Adds context support at the didkit level for CLRs (https://www.imsglobal.org/spec/clr/v2p0)
Updates wasm binary to include contexts for CLRs!
I actually added contexts for OBv3 extensions, CLRs, and data integrity!
None!
Copy/paste [this credential](https://www.imsglobal.org/spec/clr/v2p0#basic-clrcredential) into the CLI, change the issuer to your did (`clr.issuer.id = learnCard.id.did()`), then issue the credential! (`await learnCard.invoke.issueCredential(clr)`)

Add CLR Context

---

.changeset/stale-zoos-nail.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.d.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/didkit/src/didkit/pkg/didkit_wasm_bg.wasm.d.ts

We have gotten a bit behind upstream for SSI/Didkit, and we'd like to get back up to date because
they recently added better support for Data Integrity proofs!
Gets Didkit/SSI back in sync!
Open the CLI and verify that issuing/verifying/resolving dids, etc still works correctly!

Sync Didkit/SSI with Upstream

---

.changeset/breezy-fireants-live.md
services/learn-card-network/learn-cloud-service/src/routes/user.ts
services/learn-card-network/learn-cloud-service/test/users.spec.ts

If you already have a primary did that is associated with a did, then you try to add a did using the non-primary did, the add-did route will silently fail.
Fixes the above
Now, if there is already a different primary did, the new did gets added to the primary did's user
We're not using any of this yet, but under the sort of security model I had initially thought of, this is potentially dangerous! This means that a compromised did can just add as many dids as it wants to, and those dids can just continue to add still more dids
Try out Gerardo's `add-scouts-network` branch on `learncardapp`, and sign in with an account that you already have an LCN profile with. 
That account will have your LCN did (i.e. did:web:network.learncard.com:taylor) as the primary for that did:key,
and so on the …

Fix add-did route in LearnCloud

---

.changeset/plenty-bats-hang.md
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc-templates/src/types.ts

add boost ID issuer name

---

.changeset/popular-wolves-cough.md
services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
services/learn-card-network/brain-service/src/helpers/connection.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/credentials.ts
services/learn-card-network/brain-service/src/routes/presentations.ts
services/learn-card-network/brain-service/src/routes/profiles.ts

Right now, there are certain routes that allow users to request an infinitely large array. To deal 
with this, we are going to add paginated versions of these routes that allow consumers to still get
all that data, but one page at a time rather than all at once. In the meantime, to deal with the 
immediate problem, this PR adds hard limits to all of those routes, which will become deprecated and
ultimately removed in the future!
Infinite Array -> Max 50 Array for `connections`, `connectionRequests`, `pendingConnections`, and `getBoosts`
I had to copy over one of the functions from #345 to make the limit easier, but besides that it's just adding
limits to the above routes and a warning in their descriptions!
For a short period of time, it will be impossible to actually request all data for …

Stop-gap Limits

---

.changeset/famous-otters-marry.md
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/brain-service/src/helpers/signingAuthority.helpers.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19r9vq7ZHzNeBOPVKQ6K4EbSgOyGDfrqgc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=DQLPmO3)
In preparation for Scouts Network, we need to increase our resiliency to cold start issues that might arise. Namely, sometimes when claiming a credential, the LCN lambda times out because it aborts a long request to a SA. 
This ups the timeout of the lambda to 29s, and the SA request timeout to 21 seconds. 
This is a band-aid fix. We should aim to optimize these functions to get subsecond response times.
- [] This change does not expose new public facing endpoints that do not have authentication

Fix: Increase Lambda Timeout for LCN

---

.changeset/hip-dolphins-reflect.md
services/learn-card-network/brain-service/esbuildPlugins.cjs
services/learn-card-network/brain-service/jest-setup.ts
services/learn-card-network/brain-service/package.json
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/brain-service/src/cache/did-docs.ts
services/learn-card-network/brain-service/src/cache/storage.ts
services/learn-card-network/brain-service/src/helpers/learnCard.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/credentials.ts
services/learn-card-network/brain-service/src/routes/presentations.ts
services/learn-card-network/brain-service/src/routes/storage.ts
services/learn-card-network/learn-cloud-service/esbuildPlugins.cjs
services/learn-card-network/learn-cloud-service/jest-setup.ts
services/learn-card-network/learn-cloud-service/package.json
services/learn-card-network/learn-cloud-service/serverless.yml
services/learn-card-network/learn-cloud-service/src/cache/credentials.ts
services/learn-card-network/learn-cloud-service/src/cache/did-docs.ts
services/learn-card-network/learn-cloud-service/src/helpers/learnCard.helpers.ts
services/learn-card-network/learn-cloud-service/src/routes/storage.ts

[WE-2901] Add Caching in front of storage endpoints for LCN/LearnCloud
The badges page is really slow, in large part because of the sheer number of URIs being resolved
by LearnCloud. Each of URI resolution is a whole round-trip to Mongo, and can easily be cached by
Redis because that data basically never changes!
Adds Redis caching to LearnCloud (and LCN)'s `read` method!
- URIs are cached for 1 day, with the TTL being reset on every read
- Cache is set when storing
- If there is a cache miss, the cache is populated
- I also updated both lambdas to use the new didkit pattern
- I also noticed that did doc caching was _not_ reseting TTL on every read, so it will do that now, resulting in more cache hits when resolving dids
The TTL of 1 day can be tweaked, but I think it is pretty sane
Run …

[WE-2901] LearnCloud/LCN Simple Caching

---

.changeset/polite-bugs-hide.md
.github/workflows/chromatic.yml
packages/plugins/learn-cloud/src/plugin.ts
packages/plugins/learn-cloud/src/types.ts
services/learn-card-network/brain-service/esbuild.mjs
services/learn-card-network/learn-cloud-service/esbuild.mjs
services/learn-card-network/learn-cloud-service/lambda.ts
services/learn-card-network/learn-cloud-service/src/accesslayer/credential/read.ts
services/learn-card-network/learn-cloud-service/src/cache/credentials.ts
services/learn-card-network/learn-cloud-service/src/cache/index.ts
services/learn-card-network/learn-cloud-service/src/routes/storage.ts
services/learn-card-network/learn-cloud-service/test/storage.spec.ts

- :art: Add mget to cache object
- :art: Add multiples versions in access layer and cache for getting credentials by id
- :white_check_mark: Add tests
- :sparkles: Add batchResolve route
- :bug: Mark wasm as external when building
- :sparkles: Add plugin methods
- :sparkles: Add mongo integration
- :bookmark: Changest
[WE-2905] Allow batch resolving URIs
Right now, clients will get a list of URIs from their index plane, and then need to resolve them all.
This results in a _ton_ of requests being sent to resolve each URI, when we could more intelligently
resolve multiple of them per request
Adds a `batchResolve` method that resolves multiple URIs
- Adds smarter access layer and cache methods for requesting multiple things
- Adds an `mget` method to our cache object that uses `mget` when …

[WE-2905] Batch Resolve URIs

---

.changeset/rude-impalas-ring.md
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/brain-service/src/cache/challenges.ts
services/learn-card-network/brain-service/src/cache/index.ts
services/learn-card-network/brain-service/src/routes/utilities.ts
services/learn-card-network/learn-cloud-service/serverless.yml
services/learn-card-network/learn-cloud-service/src/cache/challenges.ts
services/learn-card-network/learn-cloud-service/src/cache/index.ts
services/learn-card-network/learn-cloud-service/src/routes/utilities.ts

[WE-2906] Batch set challenges in Redis
Right now, when setting valid challenges via `getChallenges` route, we are creating one promise per
challenge (~100 promises per request), which could easily overwhelm the lambda
Sets all challenges in one promise/Redis request
Adds `mset` cache method that uses Redis pipelining to set multiple keys if TTL needs to adjusted,
and `mset` otherwise
It would be much faster to be able to use `mset` directly, but because we want these to expire, we
(no matter what) _must_ end up using a pipeline to set the expiration on every key. I haven't done
benchmarking to see if it would be faster to `mset` first then use `expire` on all keys, but for
simplicity chose to just use `setex` for all keys in a pipeline
Run the test suite!

[WE-2906] Batch Set Challenges in Redis

---

.changeset/smart-cameras-fold.md
pnpm-lock.yaml
services/learn-card-network/learn-cloud-service/package.json
services/learn-card-network/learn-cloud-service/src/accesslayer/user/create.ts
services/learn-card-network/learn-cloud-service/src/accesslayer/user/delete.ts
services/learn-card-network/learn-cloud-service/src/accesslayer/user/read.ts
services/learn-card-network/learn-cloud-service/src/accesslayer/user/update.ts
services/learn-card-network/learn-cloud-service/src/cache/credentials.ts
services/learn-card-network/learn-cloud-service/src/cache/index.ts
services/learn-card-network/learn-cloud-service/src/cache/indexPlane.ts
services/learn-card-network/learn-cloud-service/src/cache/user.ts
services/learn-card-network/learn-cloud-service/src/routes/indexPlane.ts
services/learn-card-network/learn-cloud-service/src/routes/user.ts
services/learn-card-network/learn-cloud-service/test/indexPlane.spec.ts
services/learn-card-network/learn-cloud-service/test/users.spec.ts

- :white_check_mark: Flush cache in user/index plane tests
- :label: Update return type for cache.keys
- :label: Add doc comment for user cache ttl
- :arrow_up: Add json-stringify-deterministic dep
- :zap: Add caching to users via access layer methods
- :zap: Cache index plane
- :bug: Allow adding a did if its user is only itself
[WE-2902] Add Caching for LearnCloud Index
Right now, the `index.get` call can sometimes take a _very_ long time (~3-4s)! We can mitigate this
by adding Redis caching in front of it, so long as we generously flush the cache when performing write
operations
Adds caching to index plane and users
- Cache the `index.get` method
- Flush the cache for all of a users dids on any of the other `index` methods, as well as when changing the dids of a user
- Add caching in …

[WE-2902] LearnCloud Index Plane Caching

---

.changeset/popular-beers-walk.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.d.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/didkit/src/didkit/pkg/didkit_wasm_bg.wasm.d.ts

[WE-2903] Add Caching to DID Resolution in Didkit
Something slowing down some of our endpoints considerably is that we are resolving the same did:web
multiple times per request. This can easily be defeated by simply caching did:web resolution for a
short period of time
Adds a 10 second cache within `ssi` to did:web resolution
See [this commit](https://github.com/TaylorBeeston/ssi/commit/181b7815e2ee195dfdf1564d585dc642193c665d)
I picked 10 seconds semi-arbitrarily, because I wanted to make sure we don't cache for too long in the
event that a did actually _does_ change!
Open the CLI, then run `await learnCard.invoke.resolveDid('did:web:network.learncard.com:users:taylor')` multiple times.
The first one should be considerably slower than subsequent calls (which will be almost instant!)
If …

[WE-2903] Did-Web Caching

---

.changeset/thirty-zebras-train.md
packages/react-learn-card/src/components/VCDisplayCard2/VC2BackFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

This PR adds support for overriding sections of the VC display card **backface**.
1. add prop to override the criteria section
2. add prop to override the about section
```javascript
customDescription?: React.ReactNode;
customCriteria?: React.ReactNode;
```

VC Backface Overrides

---

.changeset/red-steaks-prove.md
packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

Add support for displaying a subject's **did** below the subject's name.

add prop to display subject did

---

.changeset/blue-dolphins-repair.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js

Credentials signed using SECP256r1 (P-256) will currently fail validation with a messaging saying
"P-256 is not supported". Fortunately, this was trivial to add support for within didkit
Fixes above error
Basically none, just a teeny tiny bit more wasm size
Open the CLI in this branch (`bun run nx start cli --skip-nx-cache`), and verify the following credential:
```
{
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.2.json",
"https://w3id.org/security/data-integrity/v1"
],
"id": "urn:uuid:d871d333-ee2f-411b-8fa2-4da988fa8fed",
"type": [
"VerifiableCredential",
"OpenBadgeCredential"
],
"name": "JFF x vc-edu PlugFest 3 Interoperability",
"issuer": {
"type": [
"Profile"
],
"id": …
```

P-256 Support

---

.changeset/empty-planets-try.md
services/learn-card-network/brain-service/didWebLambda.ts
services/learn-card-network/brain-service/lambda.ts
services/learn-card-network/brain-service/serverless.yml
services/learn-card-network/learn-cloud-service/didWebLambda.ts
services/learn-card-network/learn-cloud-service/lambda.ts
services/learn-card-network/learn-cloud-service/serverless.yml

LearnCloud's main did:web route has been randomly throwing 500s, and it looks like it's because the
connection to Mongo is failing (something that doesn't even need to happen for did:web!)
Packages each lambda function separately and moves the did web handler into its own file, meaning that
all the mongo code doesn't even get packaed with that lambda!
I did the same change for LCN, then immediately realized that we actually have to connect to Neo4j
for the did:web route in order to create each user's did doc =/ thankfully we aren't seeing the same
error there (yet)
I'm not sure! I checked it by deploying to my local AWS and verifying that did:web still worked...

Optimize did:web routes

---

.changeset/breezy-dancers-enjoy.md
packages/plugins/didkit/src/didkit/index.ts

Upstream (ssi) considers a VC invalid if its issuer is different than the issuer of the Status List
credential that it points to. This isn't in any specifications (that I could find), and I think it's
actually something that should be expected
Updates our fork to allow those VCs to be valid
Try verifying the following credential both on main and on this branch:
```json
{
"type": [
"VerifiableCredential",
"OpenBadgeCredential"
],
"name": "James Chartrand - Bachelor's Degree in Mathematics",
"issuer": {
"url": "https://digitalcredentials.mit.edu/",
"type": "Profile",
"name": "DCC Demo University",
"image": {
"id": "https://github-production-user-asset-6210df.s3.amazonaws.com/206059/282835374-3f3e1476-fd1e-4c8f-a560-5cfb4017bbc3.png",
"type": "Image"
},
"id": …
```

Fix Issuer Mismatch False Positive

---

.changeset/honest-boxes-argue.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

This PR allows the front facing action button on the VC display card to be customized through the following prop
`customFrontButton`

VCDisplayCard updates - allow front face button customization

---

.changeset/nine-maps-destroy.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

Fix: VCDisplayCard2 bug on iosSafari with resizing header

---

.changeset/lucky-dogs-punch.md
.changeset/nine-maps-destroy.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

Fix syntax error

---

.changeset/pretty-hairs-chew.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
packages/react-learn-card/src/components/RoundedSquare/RoundedSquare.tsx

https://welibrary.atlassian.net/browse/LC-25
Add missing alt tags

fix: [LC-25] Add alt tag to BoostGenericCard and BoostSmallCard components

---

.changeset/curvy-monkeys-jog.md
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc-templates/src/types.ts

This PR updates the context so we can support storing skills on a boost. 
```javascript 
skills: {
'@id': 'lcn:boostSkills',
'@container': '@set',
'@context': {
category: {
'@id': 'lcn:boostSkillCategory',
'@type': 'xsd:string',
},
skill: {
'@id': 'lcn:boostSkill',
'@type': 'xsd:string',
},
subskills: {
'@id': 'lcn:boostSubskills',
'@container': '@set',
'@type': 'xsd:string',
},
},
},
```

Add skills to context

---

.changeset/stale-coats-clap.md
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/read.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
services/learn-card-network/brain-service/test/consentflow.spec.ts

I noticed that withdraw events weren't showing up in the contract terms transaction history
Fixes the thing
The relationship that was being created for withdraw events was backward =(
None
Run the test suite!
I added a test specifically for this

Fix Transaction History not Displaying Withdraw Events

---

.changeset/shaggy-cycles-clap.md
packages/react-learn-card/src/assets/icons/idIcon.svg
packages/react-learn-card/src/constants/icons.ts

This PR fixes the ID icon used on the wallet squares so it matches the new icons

fix wallet id icon

---

.changeset/wild-plums-cover.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateBackFace.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCardSkillsCount.tsx

This PR adds the skills widget to the certificate backface

Display skills widget

---

.changeset/happy-cooks-divide.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/VCDisplayCard2/SelectedSkills.tsx
packages/react-learn-card/src/components/VCDisplayCard2/SkillsBox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/Subskill.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCardSkillsCount.tsx
packages/react-learn-card/src/helpers/credential.helpers.tsx

This PR adds the skills widget to the certificate display type
Confirm the certificate display type VC renders the skills count up front & the skills on the backface

Add Skills widget to certificate view

---

.changeset/thirty-seals-trade.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCardSkillsCount.tsx

- Reverted the weird scroll container thing
- Added a white background around skill counts
Link into LCA and look at boosts with skills!

Skills Polish

---

.changeset/serious-dolphins-brake.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

**Per Amy's request, we want keep the background images to remain as is for Normal boost types.**

Revert background changes for normal boost types

---

.changeset/loud-berries-enjoy.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateBackFace.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VC2BackFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDIsplayCard.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDisplayFrontFace.tsx

This PR adds support for showing a details button, if needed. 
1. adds a new prop `showDetailsBtn: boolean = false` to the <VCDisplayCard />, 
- a details button is now shows on all VC display types. 
https://github.com/learningeconomy/LearnCard/assets/40479121/0733f404-5586-4238-b858-2c03b6a59dcd
https://github.com/learningeconomy/LearnCard/assets/40479121/f5831f61-3936-4dcd-8d6e-690488c6f57d

Add Details button (ID, Cert) VC display types

---

.changeset/nice-rivers-hear.md
examples/chapi-example/.astro/settings.json
examples/chapi-example/src/pages/index.astro
packages/plugins/chapi/src/chapi.ts
packages/plugins/chapi/src/types.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18l9xUAlgR47SpRIBkz9pTuOqjU9bfk8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=jHA-fjM)
CHAPI supports sending multiple credentials in the store event. 
The Example CHAPI repo only demonstrated storing a single credential via CHAPI store event. This adds support for multiple credentials sent via chapi, in the chapi plugin and the example chapi site.
- In the examples/chapi-example repo, run `pnpm start` and try the new multi credential chapi store button. And the original single store vc button

Feat: Support Multiple VCs sent through CHAPI Store Event

---

.changeset/sharp-turtles-punch.md
packages/learn-card-types/src/lcn.ts

As part of the redesign for consenting, I found it would make sense to make sharing more granular, so
this allows terms to specify their sharing options per category rather than just for the whole set of terms
Granular sharing options
Adds a `shareUntil` for each credential category
The global sharing options are kind of weird now but I didn't want to make a breaking change by removing it
Run the test suite for the brain service!

Granular Sharing Options

---

.changeset/eleven-taxis-know.md
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc-templates/src/types.ts
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.stories.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDIsplayCard.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDisplayFrontFace.tsx

This PR adds the following changes 
1. adds a prop for passing in a custom component to override the content section of the 
ID-VC display. 
2. updates the VC template to support storing a `groupID`

Store groupID on VC 🥑

---

.changeset/big-apricots-promise.md
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js

Webpack likes to freak out if this URL statement (that is unreachable) gets left in
Removes that statement

Didkit URL/import.meta.url fix

---

.changeset/heavy-starfishes-hang.md
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDIsplayCard.tsx

1. Adds a prop for hiding the gradient on the VC backface
2. Flips the gradient displayed on the VC frontface

add hideGradientBackground prop 

---

.changeset/thin-pets-deliver.md
packages/plugins/chapi/package.json
pnpm-lock.yaml

There is a recent, serious breaking issue that is occuring due to CHAPI's `credential-handler-polyfill`
patching `navigator.credentials.get`. We have "fixed" this already by wrapping it in a try/catch,
but upstream they have actually fixed it using a `Proxy`.
Bumps to latest `credential-handler-polyfill` version to fix the above issue
Confirm you have a browser that was broken before by linking `@learncard/init` to LCA, removing the
try/catch around the `loadOnce` call in the CHAPI plugin, lowering the version of `credential-handler-polyfill`
in the CHAPI plugin to 3.2.0, then rebuilding the CHAPI plugin and `@learncard/init`. You should see
the wallet fail to initialize. If you _do_, then bump `credential-handler-polyfill` back to 3.2.1
and try it. It should now work!

Bump credential-handler-polyfill version

---

.changeset/few-maps-mate.md
.changeset/wet-bags-sniff.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateBackFace.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18j8F7zMNMPb2OKVzyd4bMsSDbk5QVM84%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=VnjpUoy)
[LC-246](https://welibrary.atlassian.net/browse/LC-246)
The claim certificate screen looks broken because the Details button is massive and takes up most of the screen (see below). This fixes that
Then:
Now:
- Run lca hooked up to local react-learn-card
- Go to the claim credential screen ([handy localhost link](http://localhost:3000/claim/boost?claim=true&boostUri=lc:network:network.learncard.com/trpc:boost:4c34c848-d384-4b89-9b2f-540c2d9ac904&challenge=3a66077a-16a2-47a3-ae89-33efbaccaba1)) and verify that it no longer looks …

[LC-246] Fix broken-looking claim certificate screen

---

.changeset/lemon-beers-sit.md
services/learn-card-network/brain-service/src/routes/storage.ts
services/learn-card-network/brain-service/test/storage.spec.ts

[LC-238] [Usersnap] Too long to load
It takes a loong time to resolve a boost from a claim link rn because we have to fully instantiate a
LearnCard and do the whole DID Auth dance before we can even begin resolving the boost, even though
it can technically just be resolved without all of that!
This opens up the resolve route so that you don't need to do DID Auth to resolve something from the
LCN!
- `didAndChallengeRoute` -> `openRoute`
- Thank you tRPC for making this so easy!
- I also had to update the resolve API route to move the URI to a query param!
Easiest way is to just run the test suite, but if you want to really test it, run it locally, connect to
it via the CLI (`let test = initLearnCard({ seed: 'a', network: 'http://localhost:3000/trpc' })`), store a credential
(`let uri = …

[LC-238] Open Up the Resolve Route

---

.changeset/brown-dots-switch.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx

This changes the formatting of the boost generic card to fix an issue mentioned in:
https://welibrary.atlassian.net/browse/LC-280
with the change from Amy:
Basically this changes the stucture from this:
```
<section> {Title Stuff}</section>
<section> {Other Stuff}</section>
```
```
<section>
{Title Stuff}
{Other Stuff}
</section>
```
This should fix the above issue seen in the screenshot

[LC-280] chore: Update boost generic card spacing and formatting of content

---

.changeset/empty-schools-deliver.md
packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1DuUAMjWQH5gHYQ8Gcav0yI7YWtAZMp0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=oSJdN4Z)
LC-232
Long issuer names with no spaces (e.g. dids) are too big, they spill onto a second line and make things look weird
Now we truncate issuer names at 20 characters instead of 25
Truncate issuer name at 20 instead of 25 characters
- provide a long name for the `issuerOverride` prop for VCDisplayCard2 however you like (e.g. using react dev tools or hardcoding one in VCDisplayCardWrapper2.tsx in learn-card-base)
- view the credential and confirm that the long name fits on one line

[LC-232 tangent] Truncate Issuer name at 20 characters

---

.changeset/late-badgers-explain.md
packages/react-learn-card/src/components/RoundedSquare/RoundedSquare.tsx

This PR adds the description to the different categories in the wallet section.
This PR goes in conjunction with this [PR 447](https://github.com/WeLibraryOS/learncardapp/pull/447) in learncardapp.
https://welibrary.atlassian.net/browse/LC-199

[LC-199] Wallet description

---

.changeset/hungry-donkeys-change.md
.changeset/stupid-dodos-double.md
packages/learn-card-network/brain-client/src/index.ts
packages/learn-card-network/cloud-client/src/index.ts

If you try to batch too many requests together, AWS will reject the request!
Sets a Max URL Length to stop that from happening (https://trpc.io/docs/client/links/httpBatchLink#setting-a-maximum-url-length)
Make a ton of boosts in LCA, then see if the live package starts giving you CORS errors (CORS is a red herring here), then use this branch and see if they go away!

Set Max URL Length in Batch Links

---

.changeset/selfish-ways-tease.md
services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

I noticed that managed boosts were showing up in the wrong order, did some digging and then found
some fairly serious issues from the pagination PR! This PR fixes what I found
Fixes the ordering and has correct pagination logic
- Fixes sort order of the `getBooostsForProfile` function
- Correctly gets the created by date in `getBoostsForProfile` (old wasn't working because of being able to match for admin_of)
- Returns the correct amount of boosts when paginating (was accidentally returning `limit` + 1)
- Adds the cursor correctly (was only adding a cursor if a cursor was specified)
- Repeats above fixes for all paginated methods as I found them
Just run the test suite!

Pagination Hotfixes

---

.changeset/sharp-buses-join.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx

[LC-320] Signature Cut off on Certificate
The text style for signatures on the front face of the certificate display add an ellipsis and cut off
the bottom part of letters that go down (like lower case g)
Updates the style like we talked about on the dev call yesterday to not do that
If someone had an egregiously long name it could potentially take up a lot of vertical real estate
Build/link LCA locally and then go look at the front face of an issued Certificate. If you don't have a good
test one with a long name, you can just inspect the element and manually change that text to something long
iOS stuff I suppose

[LC-320] Signature Tweaks

---

.changeset/red-zoos-cover.md
packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
packages/react-learn-card/src/types/index.ts

1. Adds prop for passing in a custom Draft state component for boosts
2. Removes (!) from Boost! -> Boost

[LC-292] - Boost Draft State Changes

---

.changeset/afraid-schools-sleep.md
packages/react-learn-card/src/components/VCDisplayCard2/VC2BackFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDIsplayCard.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCIDDisplayFrontFace.tsx

This PR fixes an issue where elements on the VC display card would warp when flipping the card.
1. the `inverseFlipId` was added to several child elements to cancel the parent animation when flipping the card. 
> The left hand side is the current behavior
> The right hand side is the changes made on this branch
https://github.com/user-attachments/assets/4f6c2ccb-ff90-42ff-978f-2fdd60cbc3b5
1. locally link react-learn-card using this branch 
2. confirm elements are **NOT** warping anymore when flipping the VC card

[LC-309] - fix VC card warping on flip

---

.changeset/spotty-olives-fail.md
services/learn-card-network/learn-cloud-service/src/routes/user.ts
services/learn-card-network/learn-cloud-service/vitest-setup.ts

This fixes a weird race condition (I think)

Atomicity Test

---

.changeset/curly-pans-repair.md
packages/learn-card-core/README.md

> Updates the `.readme`, to surface using LearnCloud for storing, retrieving, & publishing credentials 
> in place of Ceramic || IDX. 
Note: Additional changes to the LearnCard docs on GitBook have been submitted for review.

[LC-355] - Update LearnCard core readme

---

.changeset/few-bulldogs-draw.md
packages/plugins/learn-cloud/src/plugin.ts

Chris noticed an issue where the LearnCloud plugin is not correctly resolving LearnCloud URIs
The logic I added for resolving from other LearnClouds will often false positive and then weirdly
always insert https so it fails when doing local dev
Better URI comparison! Strip the protocol and URL encode colons!

[Hotfix] LearnCloud Plugin resolving URL encoded URIs on localhost

---

packages/react-learn-card/src/components/VCDisplayCard2/TopLevelSkill.tsx

This PR changes the font size for the skill text on the back of the boost.
https://welibrary.atlassian.net/browse/LC-395
**Before**
**After**

[LC-395] Change skill text size

---

.changeset/mean-swans-flow.md
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeCornerIcon.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeImageDisplay.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeRibbon.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
packages/react-learn-card/src/components/svgs/ScoutsLogo.tsx
packages/react-learn-card/src/helpers/credential.helpers.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1ikOgpi5FAFrITOmMT9ak1EtPgZwqfco%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=fTkPgIe)
[LC-378](https://welibrary.atlassian.net/browse/LC-378)
Support Merit Badge display in LearnCard app (called Award Display in LCA). This PR checks for `displayType === 'Award'` and uses the MeritBadge display if so. Uses the proper colors based on credential type.
Support Merit Badge display in LearnCard App
- Run learncardapp with branch `lc-378` with @learncard/react linked to this local react-learn-card
- Select the "Award" display type, Next, and ensure the preview looks like the Scouts merit badge display

[LC-378] Support for Merit Badge (aka Award) display in LearnCard App

---

.changeset/sharp-cats-press.md
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc-templates/src/types.ts

Extends the BoostID VC template to support the following fields 
```
fadeBackgroundImage?: boolean;
repeatBackgroundImage?: boolean;
idThumbnail?: string;
accentFontColor?: string;
idBackgroundColor?: string;
repeatIdBackgroundImage: boolean;
idDescription?: string;
```

Extend boostID template

---

.changeset/nervous-apples-shake.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx

This PR makes the credentials wider on smaller screens to give more room for titles and text.
Look at the [learncardapp PR](https://github.com/WeLibraryOS/learncardapp/pull/592) in conjunction with this one!
https://welibrary.atlassian.net/browse/LC-627
https://github.com/user-attachments/assets/a538ae35-9e3d-43a6-bcc3-eafc3e4c7a1e

[Lc-627] Give credentials more room

---

.changeset/tender-mice-join.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertDisplayCardSkillsCount.tsx
packages/react-learn-card/src/types/index.ts

This PR adds the skills count to the boosts in the Skills Modal. I changed the styling and order of the elements to the CertDisplayCardSkillCount component based on certain props passed in.
This PR goes in conjunction with this [PR](https://github.com/WeLibraryOS/learncardapp/pull/600) over on learncardapp.
https://welibrary.atlassian.net/browse/LC-549
To polish up the skills modal by adding a skills count to the boosts.

[LC-549] Polish Skills Modal

---

.changeset/tender-penguins-greet.md
packages/plugins/vc-templates/src/templates.ts

Fixes the place where the top level styles of the credential should be stored

fix where top level styles are being stored

---

.changeset/olive-jeans-grow.md
.changeset/rotten-apples-invite.md
.changeset/slow-carrots-dream.md
.changeset/sweet-dots-tan.md
packages/learn-card-types/src/lcn.ts
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/accesslayer/boost/create.ts
services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
services/learn-card-network/brain-service/src/accesslayer/boost/update.ts
services/learn-card-network/brain-service/src/constants/neo4j.ts
services/learn-card-network/brain-service/src/helpers/neo4j.helpers.ts
services/learn-card-network/brain-service/src/models/Boost.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/types/boost.ts
services/learn-card-network/brain-service/test/boosts.spec.ts
services/learn-card-network/brain-service/test/helpers.spec.ts

[LC-657] Boost Resolver Updates
[LC-658] $regex in queries
[LC-659] getSiblingBoosts
[LC-660] getFamilialBoosts
[LC-661] Add cosmetic fields that can be updated after a boost has been published
There are some small blocking issues for troops
Implements some of them!
- You can now use $regex in boost queries (i.e. `learnCard.invoke.getPaginatedBoosts({ query: { category: { $regex: /nice/i } } })`)
- You can now get/count boost siblings with `getSiblingBoosts` and `countSiblingBoosts`
- You can now get/count children/parents/siblings in one call with `getFamilialBoosts` and `countFamilialBoosts`
- You can now add arbitrary data to a boost that can be updated after publishing via the `meta` field
Having to inflate/deflate meta on the Boost made the boost create helper a tiny bit slower. I …

[LC-657] (Part 1) Boost Resolver Updates

---

.changeset/silver-bugs-lick.md
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc-templates/src/types.ts

This PR updates the Boost template definitions by adding support for family titles and emojis. Specifically, it introduces the following:
1. Adds support for storing an Emoji
```javascript
export type BoostEmoji = {
activeSkinTone: string;
unified: string;
unifiedWithoutSkinTone: string;
names: string[];
imageUrl: string;
};
```
3. Adds support for storing family titles 
```javascript
export type BoostFamilyTitleOption = {
plural: string;
singular: string;
};
export type BoostFamilyTitles = {
guardians: BoostFamilyTitleOption[];
dependents: BoostFamilyTitleOption[];
};
```

Extend Boost Template definitions

---

.changeset/hip-eels-double.md
packages/plugins/learn-card-network/src/plugin.ts
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

For a second there, I thought that it was possible to resolve a `Boost` without getting its `meta`
field because of the neogma thing. Turns out that was not the case, but I added tests for it anyways.
Kyle also noticed that the types/implementation in the `updateBoost` plugin method were wrong!
See above
- Adds a bunch of tests making sure that `meta` correctly shows up any way that you get a `boost`.
- Changes `updateBoost` plugin method to make the `credential` optional
None! =)
Run the test suite!

Smol Boost Tweaks

---

.changeset/flat-countries-cheat.md
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19P7c5GPQfAHVaPSDqn4xxEdlQQJ64Qxs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=DTDuoCh)
[LC-734](https://welibrary.atlassian.net/browse/LC-734)
We want to remove the auth check from getBoost so that people who don't have any permissions on the boost can see the edits made to it. e.g. if you haven't yet claimed a boost that you were issued you currently can't see the edited information (like the updated name). This fixes that issue so everyone can see the edits.
Remove auth check on getBoost so that everyone can see edits!

[LC-734] Remove permission check from getBoost

---

.changeset/tall-wolves-obey.md
packages/learn-card-types/src/lcn.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/create.ts
services/learn-card-network/brain-service/src/models/ConsentFlowContract.ts
services/learn-card-network/brain-service/src/routes/contracts.ts
services/learn-card-network/brain-service/src/types/consentflowcontract.ts
services/learn-card-network/brain-service/test/consentflow.spec.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18NdTBolHA0uhuEOkscLVZkLsB2iWU5Y%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=XzUevhI)
[LC-735](https://welibrary.atlassian.net/browse/LC-735)
We need a flag on ConsentFlow contracts to indicate if they should trigger the family/guardian approval flow. Enter: `needsGuardianConsent`
run the tests!

[LC-735] Add needsGuardianConsent flag for ConsentFlow contracts

---

.changeset/small-feet-search.md
packages/learn-card-types/src/lcn.ts
services/learn-card-network/brain-service/src/accesslayer/profile/read.ts
services/learn-card-network/brain-service/src/models/Profile.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/test/profiles.spec.ts

Child Profiles shouldn't surface in search
Add `isPrivate` to a profile to allow yourself to not show up in search!
This is a very simple privacy control. In the future we may want a privacy/permissions object with
more fine-grained control
pnpm test

Private Profiles

---

.changeset/silly-guests-impress.md
packages/learn-card-types/src/lcn.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/create.ts
services/learn-card-network/brain-service/src/models/ConsentFlowContract.ts
services/learn-card-network/brain-service/src/routes/contracts.ts
services/learn-card-network/brain-service/src/types/consentflowcontract.ts
services/learn-card-network/brain-service/test/consentflow.spec.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Hm4zuFlVQGCpVkMbFHgElNM0sflQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=uvR2rgw)
[LC-750](https://welibrary.atlassian.net/browse/LC-750)
ConsentFlow contracts need a redirectUrl field if we’re going to support things like LaunchPad app → connect → go through flow → redirect to custom app url
Add redirectUrl to ConsentFlow contracts
- `cd .../LearnCard/services/learn-card-network/brain-service`
- `pnpm exec nx test`
https://app.gitbook.com/o/6uDv1QDlxaaZC7i8EaGb/s/FXvEJ9j3Vf3FW5Nc557n/~/changes/85/learn-card-sdk/consentflow

[LC-750] Add redirectUrl to ConsentFlow contracts

---

.changeset/mean-worms-hug.md
.changeset/silver-ears-raise.md
packages/plugins/learn-cloud/src/helpers.ts
packages/plugins/learn-cloud/src/types.ts
services/learn-card-network/learn-cloud-service/src/helpers/encryption.helpers.ts
services/learn-card-network/learn-cloud-service/src/routes/indexPlane.ts

When storing/querying in LearnCloud, currently a hardcoded hash function is used
Allows using `_learnCard.invoke.hash` for that!

Customizeable Hash Function

---

.changeset/hungry-toes-swim.md
packages/react-learn-card/src/components/RoundedSquare/constants.ts

chore: Fix import to replaced graphic

---

.changeset/lovely-apes-report.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx

This PR goes in conjunction with this [PR](https://github.com/WeLibraryOS/learncardapp/pull/667) in learncardapp. It adds the change Donny requested to update the full view of the certificates and awards with the type and category based on the design from Amy.
https://welibrary.atlassian.net/browse/LC-758
https://github.com/user-attachments/assets/0070909e-98f9-406d-8fea-f558105327ca

[LC-758] Add type and category to CertificateFrontFace and MeritBadgeFrontFace

---

.changeset/forty-pianos-doubt.md
packages/plugins/learn-card-network/src/types.ts
services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/test/boosts.spec.ts

[Lc-783] Include Uncles, Cousins, and Nephews in `getFamilialBoosts`
Allow getting uncles, cousins, and nephews in getFamilialBoosts and countFamilialBoosts
Adds an `includeExtendedFamily` flag to do that
Run the test suite =)
I added a test for both resolvers

[LC-783] Uncles and Cousins and Nephews, Oh my!

---

.changeset/beige-swans-exercise.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeDisplayCard.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx

This previous PR - https://github.com/learningeconomy/LearnCard/pull/607 had an error building due to 'property achievement does not exist on type'. To fix this issue, I passed the formattedDisplayType from learncardapp to LearnCard, to no longer run into this error and be able to see the type and category for the full view of certs and awards.
This is the [learncardapp PR](https://github.com/WeLibraryOS/learncardapp/pull/672) that needs to run with this one.
https://welibrary.atlassian.net/browse/LC-758
To fix the issue with the build and be able to display the type and category on the full view for certs and awards
https://github.com/user-attachments/assets/c6caa958-6b21-44a1-a390-15a34833935c

[LC-758] Fix full view for certs and awards

---

.changeset/cold-tomatoes-impress.md
services/learn-card-network/learn-cloud-service/src/xapi.ts

Fix: Add Server Error Messages for xAPI

---

.changeset/selfish-beds-search.md
services/learn-card-network/learn-cloud-service/src/cache/rsa.ts
services/learn-card-network/learn-cloud-service/src/helpers/auth.helpers.ts
services/learn-card-network/learn-cloud-service/src/helpers/crypto.helpers.ts
services/learn-card-network/learn-cloud-service/src/oidc.ts
services/learn-card-network/learn-cloud-service/src/xapi.ts

XAPI isn't working because the OIDC key pair keeps changing
The getDeterministicRsaKeyPair function wasn't actually deterministic. It is now
Actually deterministic RSA keypair creation. This is slow, so I have it pretty heavily cached both at
init time and with redis
Rolling your own crypto is always kind of risky, so we may likely want to update this to just accept like an environment variable or something.
This new determinsitis RSA function is a huge potential security hole that will need to be examined and closed up soon!
Run the E2E tests!

Fix OIDC key changing

---

.changeset/six-donkeys-cough.md
docs/README.md
docs/docs/core/index.md
docs/docs/react/index.md
examples/chapi-example/src/components/CredentialListItem.tsx
examples/chapi-example/src/components/CredentialStorage.tsx
examples/chapi-example/src/pages/index.astro
packages/learn-card-core/README.md
packages/plugins/ceramic/README.md
packages/plugins/idx/README.md
packages/plugins/learn-cloud/README.md

This commit updates all documentation and code examples to consistently use LearnCloud instead of the legacy Ceramic/IDX storage solution. Changes include:
- Updated README files in multiple packages
- Fixed code examples in documentation
- Updated example applications to use LearnCloud API
- Added deprecation notice to IDX plugin documentation
- Replaced references to 'stream ID' with 'URI'

Docs: update Ceramic/IDX references to LearnCloud

---

.changeset/strong-experts-melt.md
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts

Fix Claim Hook Processing When Claiming a Boost with a Claim Link

---

.changeset/unlucky-elephants-doubt.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx

This PR fixes the issue of the missing achievement image on certificate type views for the issuer. The issue was found with the LearnFleet Academy boost. 
https://welibrary.atlassian.net/browse/LC-819
**Before**
**After**

[LC-819] Fix missing achievement image on Certificate Views

---

.changeset/violet-nails-trade.md
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/contracts.ts

[LC-775] Interactive LearnCard Demo with Seeded Content
Autoboosts had broken logic where they were auto accepted and a notification was sent when it should have been the opposite
Fixes the autoboost logic
When an auto boost is sent. It should _not_ be marked as auto received, and it also should _not_ send a notification.
This PR does that. We don't want it auto-received because then it won't show up in the LCA logic that grabs
all credentials written to your contracts that you haven't accepted yet, and we don't want a notification
because that's a confusing UX in LCA.
Also, I refactored `sendBoost` to take an object instead of like seven positional args lol
In the future, this _should_ send a notification, just a different kind!
Just run all the tests =)

[LC-775] AutoBoost Notification Fix

---

packages/plugins/simple-signing-plugin/package.json

Make simple signing plugin public

---

.changeset/mean-ears-fry.md
packages/learn-card-types/src/lcn.ts
services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/read.ts
services/learn-card-network/brain-service/src/routes/contracts.ts
services/learn-card-network/brain-service/test/consentflow.spec.ts

Right now, there's no way to see what autoboosts are associated with a contract!
Includes an `autoboosts` string array that is the URIs of all autoboosts associted with a contract
It might be better to have a separate route for getting autoboosts to handle things like pagination,
but I think for right now this is okay.
Just run the test suite =)
I wrote tests for all relevant routes

Return Autoboosts in Contract Details

---

packages/learn-card-contexts/_headers
packages/learn-card-contexts/contexts/boosts/1.0.0.json

Feat: Add Boost JSON-LD Contexts as package

---

.changeset/sixty-ghosts-join.md
services/learn-card-network/brain-service/src/routes/contracts.ts
tests/e2e/tests/consentflow.spec.ts

[LC-892] [Create Write to Contract with Signing Authority Route](https://welibrary.atlassian.net/browse/LC-892?atlOrigin=eyJpIjoiMjJlNDEyYTNhYTg1NDNmMmIyNDYyNWE0OGJkM2RiOTYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
We need an HTTP-Friendly route similar to the send boost route to write credentials to contracts
Mimics #646 but for writing to contracts
Hopefully none!
Run the E2E tests!
There is a similar awesome E2E test using auth grant with minimal scope =)
[LC-892]: https://welibrary.atlassian.net/browse/LC-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-892] HTTP-Friendly Write to Contract

---

.changeset/smart-ducks-serve.md
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/contracts.ts

Fix: Change to query param

---

README.md

Add DW Badge

---

.github/workflows/deploy.yml
packages/learn-card-types/src/lcn.ts
services/learn-card-network/brain-service/src/models/Profile.ts
services/learn-card-network/brain-service/src/routes/profiles.ts
services/learn-card-network/brain-service/src/types/profile.ts
services/learn-card-network/brain-service/test/profiles.spec.ts

[LC-907](https://welibrary.atlassian.net/browse/LC-907)
1. Extends the user model to support 
- dob
- role
2. updates getOtherUserProfile
- omits returning DOB when viewing other profiles
3. update payload inputs for createProfile & updateProfile, now supports
- dob
- role
4. update tests, account for `dob & role`
Test with the following PR 
https://github.com/WeLibraryOS/learncardapp/pull/738
[LC-907]: https://welibrary.atlassian.net/browse/LC-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
This PR implements the following changes:
Purpose: Adds new fields 'role' and 'dob' to the LCN profile schema and updates related functionality.
Main changes:
- Adds 'role' and 'dob' fields to LCNProfileValidator in lcn.ts
- Updates profile creation, …

LC-907 - New Onboarding flow + Checklist UI 

---

.changeset/ten-yaks-leave.md
packages/plugins/didkit/src/plugin.ts
tests/e2e/tests/encryption.spec.ts

[LC-947] Fix BigInt issue
When I made JWE support in didkit, I accidentally left in that Rust serializes all numbers as BigInts, causing certain things (specifically `JSON.stringify`) to fail
Fixes that by recursively converting BigInts to numbers
This will slow down decryption a bit =(
There are end to end tests for this! =)
End to end tests
[LC-947]: https://welibrary.atlassian.net/browse/LC-947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- This PR addresses the issue of BigInts being serialized when crossing the WASM boundary in the DIDKit plugin, converting them back to Numbers.
- Adds a recursive function to convert BigInts to Numbers in the decryptDagJwe method
- Implements new tests to ensure proper handling and preservation of …

[LC-947] BigInt Thing

---

.changeset/itchy-animals-taste.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js

Now that we host our boost context, we need to inline it into SSI!
Bumps to latest ssi/didkit and updates didkit wasm payload
Pop open the CLI:
```bash
pnpm exec nx start cli --skip-nx-cache
```
Then issue a VC using the context:
```bash
let test = await initLearnCard({ seed: 'a' }); // Needed because the default LC has dynamic resolution enabled
let vc = {
"@context": [
"https://www.w3.org/2018/credentials/v1",
"https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.1.json",
"https://ctx.learncard.com/boosts/1.0.0.json",
],
"attachments": [],
"boostId": "lc:network:network.learncard.com/trpc:boost:9f50995b-8e9d-42dc-9f29-77b4a52529c2",
"credentialSubject": {
"achievement": {
"achievementType": "ext:Charmer",
"criteria": {
"narrative": ""
},
"description": "",
"id": "urn:uuid:123",
"image": …
```

Inline Boost Context

---

packages/learn-card-registries/untrusted/registry.json

This PR is adding an untrusted DID to the registry for testing purposes.
Purpose and impact:
This PR adds a new user entry to the untrusted registry JSON file.
Main changes:
- Adds a new DID entry "did:web:network.learncard.com:users:sophpotato1" to the registry
- Includes user details for "Soph Potato" with name, location, and URL
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your feedback!](mailto:product@linearb.io)** 🚀</sub>

Add untrusted issuer

---

.changeset/honest-needles-yell.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
packages/react-learn-card/src/helpers/credential.helpers.tsx

Updates the category colors to match with the latest wallet color changes made on LCA

LC-849 - colors support 

---

.changeset/open-chicken-beg.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeDisplayCard.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.stories.tsx
packages/react-learn-card/src/helpers/test.helpers.ts

[LC-996](https://welibrary.atlassian.net/browse/LC-996)
When the title and issuee / issuer names were small, the certificate and award display types were super skinny
Fixed that with a min width of 350px.
Also reworked the boost display while I was at it, so test with [this LCA PR](https://github.com/WeLibraryOS/learncardapp/pull/781)
Fix skinny certificates
Refer to the [LCA PR](https://github.com/WeLibraryOS/learncardapp/pull/781)
Storybook!
[LC-996]: https://welibrary.atlassian.net/browse/LC-996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
- This PR changes the width behavior for Certificate display, setting a max width of 400px and removing auto x margin.
- Main changes:
• Changed section class from "sm:mx-0 md:mx-auto" to "max-w-[350px] …

[LC-996] Fix certificate width

---

.changeset/large-ducks-laugh.md
packages/learn-card-cli/package.json
packages/learn-card-cli/src/index.tsx
pnpm-lock.yaml

Sometimes objects are big in CLI and you can't copy them / are too dang nested!
- adds `copy` command that takes object, string, or number and copies to clipboard, EZ-PZ.
Boot up CLI, and copy an object, string, and number!
``` 
cred = await learnCard.invoke.getTestVc()
copy(cred)
banana = "banana"
copy(banana)
hundredandthree = 123
copy(hundredandthree)
```
Purpose: Add clipboard functionality to LearnCard CLI, allowing users to copy data easily.
Main changes:
- Added 'clipboardy' dependency for clipboard operations
- Created copyFunction that handles string, object, and number types
- Integrated copy function as a global variable in CLI environment
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd …

Feat: Add copy function to CLI

---

.changeset/nervous-years-cover.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx

bump version + change set

---

.changeset/gold-carpets-add.md
packages/learn-card-contexts/boosts/1.0.1.json
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/vc-templates/src/templates.ts

We recently updated the boost context but didn't make a new version of it!
Brings back the old context as 1.0.0 and moves the new one to 1.0.1. Also inlines it in didkit and adds it to templates!
Pop open the CLI, make a new boost, and issue it!
```js
let vc = learnCard.invoke.newCredential({ type: 'boost' });
vc.credentialSubject.id = learnCard.id.did();
await learnCard.invoke.issueCredential(vc);
```

Boost 1.0.1 Context

---

.changeset/dark-games-melt.md
packages/learn-card-init/test/index.test.ts
packages/plugins/vc-templates/src/templates.ts
packages/plugins/vc/src/vc.ts
services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
services/learn-card-network/brain-service/src/routes/boosts.ts
services/learn-card-network/brain-service/src/routes/contracts.ts
services/learn-card-network/brain-service/src/routes/index.ts
services/learn-card-network/simple-signing-service/package.json
services/learn-card-network/simple-signing-service/src/routes/credentials.ts
services/learn-card-network/simple-signing-service/src/routes/index.ts

[LC-1095] Upgrade LearnCard to use VC 2.1
I found more issues with using VC 2.0 with LCN, so I went through and tried to find every instance/use
of VC 1.0 stuff across the repo and update them
Fixes sending a VC 2.0 boost via `sendBoost`
The existing E2E tests should still pass and catch this =)
[LC-1095]: https://welibrary.atlassian.net/browse/LC-1095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Purpose: Update credential handling across multiple packages to properly support Verifiable Credentials v2.0 format.
Main changes:
- Changed @context references from 2018/credentials/v1 to www.w3.org/ns/credentials/v2
- Replaced expirationDate with validFrom/validUntil fields in credential objects
- Added isVC2Format detection to conditionally …

[LC-1095] Part 3: More VC 2 Fixes

---

.changeset/chilly-eels-breathe.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
packages/react-learn-card/src/components/svgs/ThreeDotVertical.tsx
packages/react-learn-card/src/components/svgs/index.ts
packages/react-learn-card/src/helpers/video.helpers.ts

1. update 3 dot menu trigger, add opacity 
2. add support for google drive, loom - videos
3. fix youtube videos
Purpose: Refactor card thumbnails and enhance video metadata extraction for improved user experience.
Main changes:
- Replaced image tag with SVG component for three-dot vertical menu icon
- Added semi-transparent background to menu button with improved styling
- Enhanced video metadata extraction to support additional platforms (Drive, Loom)
- Added thumbnail fallback mechanisms for better visual consistency
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your feedback!](mailto:product@linearb.io)** 🚀</sub>

[LC-1132] - thumbnail polishes

---

packages/learn-card-bridge-http/package.json
packages/learn-card-cli/package.json
packages/react-learn-card/package.json
services/learn-card-discord-bot/package.json
services/meta-mask-snap/package.json

Reverts learningeconomy/LearnCard#521

Revert "⬆️ Bump the npm_and_yarn group across 5 directories with 1 update"

---

.changeset/light-maps-learn.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
packages/react-learn-card/src/components/CertificateDisplayCard/CertDisplayCardSkillsCount.tsx
packages/react-learn-card/tailwind.config.js

[LC-1147](https://welibrary.atlassian.net/browse/LC-1147)
1. align text bottom
[LC-1147]: https://welibrary.atlassian.net/browse/LC-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Purpose: Fix styling and structure issues in BoostGenericCard component to improve layout and visual consistency.
Main changes:
- Refactored card layout with flex-grow sections for better space utilization
- Simplified component structure by removing redundant divs and CSS classes
- Moved linked credentials display inside main content area instead of absolute positioning
- Added card-shadow style to Tailwind configuration for consistent elevation effects
<sub>AI-generated content may contain inaccuracies. Please …

fix: Boost Generic Card Content

---

.changeset/ten-dryers-guess.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx

center text

---

.changeset/chilly-moose-happen.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertDisplayCardSkillsCount.tsx

This PR removes the shadow around the skills in skills hub.
https://welibrary.atlassian.net/browse/LC-1167
**Before**
**After**

[LC-1167] Remove shadow around skills

---

.changeset/popular-fishes-raise.md
packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx

fixes the Accomplishments Category display text 
- Accomplishment -> Portfolio

fix portfolio category display text

---

.changeset/eleven-rockets-act.md
packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx

fixes an issue with the CircleCheckButton not being visible
Purpose: Fix BoostGenericCard component by adding z-index to ensure proper stacking of the check button overlay.
Main changes:
- Added z-index (z-20) to check button overlay div to prevent interaction issues
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your feedback!](mailto:product@linearb.io)** 🚀</sub>

fix: BoostGenericCard selective state

---

.changeset/twenty-heads-talk.md
packages/plugins/learn-card-network/src/plugin.ts

Add recipient token (trigger version bump)

---

.changeset/stupid-brooms-bow.md
packages/plugins/didkit/src/didkit/index.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.d.ts
packages/plugins/didkit/src/didkit/pkg/didkit_wasm.js
packages/plugins/didkit/src/didkit/pkg/didkit_wasm_bg.wasm.d.ts
tests/e2e/tests/presentations.spec.ts

[LC-1246] Move Data Integrity Proof context to top-level for Verifiable Presentations (parity with VCs)
I forgot to also move the context for VPs!
Does that upstream and bumps here
Run the E2E tests! There's a VP test for it
[LC-1246]: https://welibrary.atlassian.net/browse/LC-1246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LC-1246] Move VP Context

---

packages/learn-card-contexts/linked-claims/endorsement/1.0.0.json

Ctx: Add LinkedClaim Endorsement Context

---

pnpm-lock.yaml
tests/e2e/package.json
tests/e2e/tests/interoperability/dcc/credential-verification.spec.ts

We have an DCC interop test suite, but did not have a test for verifying a VP from LearnCard
Adds test for verifying VP from learncard sdk using DCC suite.
VerifierCore does not have support for verifying DID-Auth VPs, so we could not add a test for this.
Purpose: Add Digital Credentials Consortium (DCC) presentation verification interoperability test to ensure LearnCard compatibility with DCC verifiers.
Main changes:
- Added presentation verification test using the DCC verifier-core library
- Updated verifier-core dependency from 0.0.1-beta.2 to 1.0.0-beta.8
- Removed console.log debugging statements from credential verification test
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your …

chore: Add Presentation to DCC interop

---

.changeset/smart-chefs-jam.md
packages/react-learn-card/src/components/Lightbox/Lightbox.tsx
packages/react-learn-card/src/components/VCDisplayCard2/TopLevelSkill.tsx

Run this [PR](https://github.com/WeLibraryOS/learncardapp/pull/1024) with it! 
This PR fixes the broken video attachments for a credential. It also adds a change a user wanted to have the entire skill on the credential details to be clickable instead of just the circle with the number. 
https://welibrary.atlassian.net/browse/LC-1357
https://github.com/user-attachments/assets/5ba64d88-f188-458a-a38e-7cfd97d32b4a
Purpose: Fix video attachments in Lightbox component and improve skill button accessibility in VCDisplayCard2 component.
Main changes:
- Added currentItem dependency to useEffect in Lightbox to properly fetch metadata when item changes
- Refactored TopLevelSkill component to make the entire skill card clickable when sub-skills exist
- Added changeset file for patch version bump …

fix: [LC-1357] Broken video attachment and make skill button clickable

---

.changeset/clean-buckets-tan.md
packages/learn-card-types/package.json

Purpose: Update @learncard/types package version from 5.8.7 to 5.8.8 in preparation for release.
Main changes:
- Bumped @learncard/types version from 5.8.7 to 5.8.8
- Added changeset file to document the version update
<sub>AI-generated content may contain inaccuracies. Please verify before using. **[We'd love your feedback!](mailto:product@linearb.io)** 🚀</sub>

chore: Bump learn-card-types
