- .changeset/fresh-ligers-remember.md
- packages/learn-card-core/src/types/planes.ts
- packages/learn-card-core/src/wallet/base/wallet.ts
- packages/learn-card-core/src/wallet/plugins/idx/idx.ts
- services/meta-mask-snap/snap.manifest.json
[WE-2559] Add addMany method to index plane
Adding many credentials at once is a pain!
Adds optional `addMany` method to the index plane
I currently did _not_ implement an automatic fallback for plugins that don't implement the method, mostly because the types would have been a pain.
In the future, it would be cool to have plugins that don't support `addMany` explicitly to just automatically
have `add` called over and over again for them
See above screenshot in CLI
https://app.gitbook.com/o/6uDv1QDlxaaZC7i8EaGb/s/FXvEJ9j3Vf3FW5Nc557n/~/changes/iUhWHoXtD0up9HY6NFnb/learn-card-sdk/learncard-core/control-planes/index
> [WE-2561] Add addMany index plane method

- .changeset/eight-keys-hammer.md
- packages/learn-card-core/src/wallet/base/helpers.ts
- packages/learn-card-core/src/wallet/base/wallet.ts
- packages/learn-card-core/src/wallet/plugins/index.ts
- packages/learn-card-core/src/wallet/plugins/test-index/index.ts
- packages/learn-card-core/src/wallet/plugins/test-index/types.ts
- packages/learn-card-core/src/wallet/plugins/test-storage/index.ts
- packages/learn-card-core/src/wallet/plugins/test-storage/types.ts
- packages/learn-card-core/test/index.test.ts
[WE-2566] Fix Issues with Multiple Planes
There are a couple of issues currently when using a wallet with multiple plugins that implement read, store, index, or cache
Fixes the above issues
- Fixes a race condition in conglomerate `get` methods
- This was caused by using `Promise.any` on all valid plugins, assuming that all valid plugins would return _something_.
What can _actually_ happen is that one plugin can return `undefined` and cause the plugin that _can_ return something to get skipped.
This effectively means that what is returned is whatever runs _fastest_, and _not_ whatever actually resolves to something.
This has been changed to use `Promise.allSettled` and then a loop through the results to find the first plugin
that found _something_.
- Fixes an issue with deduping on the …
> [WE-2566] Fix Multi-Plane Issues

- .changeset/tricky-rocks-warn.md
- packages/learn-card-core/src/index.ts
- packages/learn-card-core/src/polyfills.ts
- packages/learn-card-core/src/types/global.d.ts
Closes #122
In contexts where modules must be fully specified, our `abort-controller` polyfill can error out due to an unmaintained package.
Skips using the polyfill logic of the unmaintained package and instead does the polyfill manually!
Import this branch into a new CRA5 app and make sure you don't run into any `abort-controller` issues
> Manual Abort Controller Polyfill

- .changeset/seven-bulldogs-design.md
- packages/learn-card-core/src/types/planes.ts
- packages/learn-card-core/src/wallet/plugins/ceramic/ceramic.ts
- packages/learn-card-core/src/wallet/plugins/idx/idx.ts
- packages/learn-card-core/src/wallet/plugins/test-cache/index.ts
- packages/learn-card-core/src/wallet/plugins/test-storage/index.ts
[WE-2575] Widen read/store types to include VPs
It would be nice to be able to upload/retrieve VPs easily from Ceramic...
Widens the types for the read/store planes to allow uploading/reading VPs as well as VCs
Also widens the cache plane types.
Also updates the Ceramic, IDX, test-cache, and test-index plugins!
Read might be a bit more tedious to work with now because you could be getting either a VP _or_ a VC,
but I don't think it will be that bad! If it proves to be annoying, I could add a flag that changes
the return type automatically.
Open up the CLI and run the following:
```js
const vp = await learnCard.invoke.issuePresentation(await learnCard.invoke.getTestVp());
const uri = await learnCard.store.Ceramic.upload(vp);
await learnCard.read.get(uri);
```
This should successfully work …
> [WE-2575] Widen Read/Store types

- .changeset/honest-buses-own.md
- packages/react-learn-card/src/components/JobListCard/JobListCard.stories.tsx
- packages/react-learn-card/src/components/JobListCard/JobListCard.tsx
- packages/react-learn-card/src/types/index.ts
This adds a prop `customButtonComponent` to allow to pass a React node into where the current button is to make it more customizable.
> Add additional prop to job listing card to override with custom button component

- .changeset/sour-bulldogs-sit.md
- packages/learn-card-types/src/lcn.ts
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- pnpm-lock.yaml
- services/learn-card-network/brain-service/src/accesslayer/boost/create.ts
- services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
- services/learn-card-network/brain-service/src/models/Boost.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/src/types/boost.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
- services/meta-mask-snap/snap.manifest.json
We need a clear delineation between boosts that are being created, and boosts that have been vacuum-sealed and ready to send to people!
This introduces a new `status` field on boosts, currently supporting:
```
LIVE 
DRAFT
```
Live status indicates the boost is published and can be sent to others. Live Boosts can not be updated or deleted.
Draft status indicates the boost is in draft state. It can not be sent to others. Draft boosts can be updated and deleted.
- updateBoost (in the LCN plugin) now supports an additional `credential` field that allows you to pass through a new base credential template for the boost
- updateBoost allows you to pass a status field in, that can flip the status of a boost from DRAFT to LIVE.
- adds support for deleting draft boosts (and preventing deleting live …
> Feat: Add Draft / Live state to Boosts

- .changeset/soft-oranges-report.md
- packages/plugins/didkit/src/didkit/index.ts
Right now, if you instantiate two LearnCards at the same time via Promise.all, it will not work and
at least one of them will totally fail!
Say goodbye to this error! 
Prior to this change, I was preventing costly re-inits of the webassembly by keeping a variable around
to check if the init function had already been ran. This results in ~9x speedup when instantiating multiple
LearnCards. However, this check was pretty crude, and if a second LearnCard wanted to come in and initialize
while the first one was currently initializing, it would just _not_ init, and then didkit would have no access
to wasm. This PR beats this by adding a more robust `generating` variable. Using this, if a second LearnCard
comes in wanting to instantiate while the init function is running from another LC, it will …
> Fix Didkit Concurrency Bug

- .changeset/few-ears-invite.md
- packages/learn-card-types/src/vc.ts
Working on the new CHAPI exchange flow, I noticed that saved credentials with `credentialStatus` were
being mutated when getting saved, and found that it's because our zod validators are too strict and
are stripping fields from `credentialStatus`!
Loosens the credential status type to not strip fields!
> Don't Strip Status

- .changeset/eleven-bikes-think.md
- packages/learn-card-types/src/lcn.ts
- services/learn-card-network/brain-service/jest.config.ts
- services/learn-card-network/brain-service/src/cache/connections.ts
- services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
- services/learn-card-network/brain-service/src/helpers/connection.helpers.ts
- services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
- services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
- services/learn-card-network/brain-service/src/helpers/signingAuthority.helpers.ts
- services/learn-card-network/brain-service/src/models/Boost.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/src/routes/profiles.ts
- services/learn-card-network/brain-service/test/profiles.spec.ts
[LC-111] Setting to "Auto-Connect" Members
We want to be able to automatically connect profiles if they share a boost!
Adds an `autoConnectRecipients` field to Boost metadata
- Boost type updated to include `autoConnectRecipients`
- `getConnections` logic updated to also search for users that share an auto-connect boost with you
- Also accounts for the case where you only have created the boost and have not actually received it!
The `getConnections` query is pretty intense right now and is definitely more in favor of a write-heavy
workload rather than a read-heavy workload, which we are more likely to see. A way past this in the future
may be to actually create an intermediary relationship directly between two profiles pointing to the
boost that connects them every single time a Boost is …
> Auto-Connect Boosts

- .changeset/many-fireants-enjoy.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/cache/invites.ts
- services/learn-card-network/brain-service/src/routes/profiles.ts
- services/learn-card-network/brain-service/test/profiles.spec.ts
https://welibrary.atlassian.net/browse/LC-21
Lets set the expiration for the add profile link to 30 Days vs 1 hour. 
Stretch Goal: Add selector to choose 24 hours, 7 days, 1 mo, never expire
Allows users to set the expiration for the add profile link to 30 Days vs 1 hour. 
The "generateInvite" function now has an `expiration` parameter and the "generateInvite: profileRoute" endpoint now takes an `expiration` as an input. 
Yes in "LearnCard/services/learn-card-network/brain-service/test/profiles.spec.ts" two new tests:
- allows setting the expiration length
- the generation date cannot be updated after creation
Running jest unit tests *OR* edit the default expiration pictured above to a very short amount of time to watch the invite fail. 
Jest unit tests and QA.
> Fix [LC-21] Expiration for add profile link

- .changeset/bright-shrimps-learn.md
- .changeset/healthy-rivers-kiss.md
- .changeset/odd-otters-watch.md
- package.json
- packages/learn-card-core/src/types/utilities.ts
- packages/learn-card-core/src/types/wallet.ts
- packages/learn-card-network/brain-client/src/index.ts
- packages/plugins/chapi/src/types.ts
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- pnpm-lock.yaml
- **:arrow_up: Bump TS to 5.5.2**
- **:sparkles: Allow changing boost VCs before sending them**
- **:bookmark: Changesets**
We've been stuck on TS 5.0.4 for a while, and I finally got that fixed today!
Also, right now, you can not actually change a boost before sending it (such as to add a `credentialStatus` field),
nor can you easily get the Brain Client object from the Network plugin
Upgrades TypeScript across the whole monorepo and allows for better flexibility when sending boosts
- Upgrade to TS 5.5.2
- In order to make this work, I had to do this weird change where I can't use `[T] extends [1 & T]` directly to determine if `T` is any, but I _can_ put that into a helper type `type IsAnyOrNever = [T] extends [1 & T] ? true : false` and use that: `IsAnyOrNever<T> ? true : false`. Don't …
> TS 5.5 Update and Send Boost Fix

- .changeset/breezy-cars-march.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
- **:sparkles: Add Boost Recipient Count**
- **:bookmark: Changesets**
[WE-3308] Aug - badge count is inaccurate
We don't have a good way to count the number of recipients for a boost
Adds a resolver to count boost recipients
- New route: `getBoostRecipientCount`
- New plugin method: `countBoostRecipients`
None!
Run test suite, run this locally and connect a learncard to it in the CLI:
```
cd services/learn-card-network/brain-service
pnpm start
```
```
pnpm exec nx start cli # Add --skip-nx-cache if it doesn't seem to be working
// Once it's open
let test = await initLearnCard({ seed: 'a', network: 'http://localhost:3000/trpc' });
let test2 = await initLearnCard({ seed: 'b', network: 'http://localhost:3000/trpc' });
// If you don't have accounts yet, make them
await …
```
> [WE-3308] Recipient Count

- .changeset/thick-tables-clean.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
[LC-270] Count on the Earned and manage tabs like in a prior Figma design
To get accurate counts, we need a count route, and that count route needs to be able to query for specific categories!
Updates get/count boost routes to accept a query
- `getBoosts`, `countBoosts`, and `getPaginatedBoosts` were all updated to accept a query
- The query is just a `Partial<Boost>`, meaning you can only do basic equality queries for now. We might want to open this up in the future to add like $in or $not or something
- `getBoosts` and `countBoosts` had to change from `GET` to `POST` in the HTTP API, because GET can't handle an object as input, and I didn't want to screw with the main API to account for that
Run the test suite. After that, to test manually, you'll need to do a couple of things:
- Run …
> [LC-270] Filter Boosts

- .changeset/serious-books-check.md
- packages/learn-card-types/src/lcn.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/read.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/test-setup.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
In order to more efficiently implement Scout troops, we need to be able to query for managed boosts
using $in
Adds the ability to use $in (like Mongo) when querying for boosts
I believe this slightly lowers performance
Run the test suite!
I added tests for all relevant routes =)
> Boost Queries with $in

- .changeset/curly-melons-share.md
- packages/learn-card-types/src/lcn.ts
- services/learn-card-network/brain-service/src/accesslayer/credential/relationships/create.ts
- services/learn-card-network/brain-service/src/accesslayer/credential/relationships/read.ts
- services/learn-card-network/brain-service/src/accesslayer/role/relationships/create.ts
- services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
- services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
- services/learn-card-network/brain-service/src/models/Boost.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/src/types/boost.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
- services/learn-card-network/brain-service/test/permissions.spec.ts
[LC-634] Back-End: Default Role when Claiming
To ease with the troops setup, we want to be able to set a default role/permissions that you get automatically
when claiming a boost
Adds the ability to give a profile default permissions at the time that they claim a boost
- Boosts now have a `claimPermissions` field on them.
- `claimPermissions` is just a regular permissions object that specifies the permissions a user gets when claiming the boost
- When setting `claimPermissions`, a new `Role` node is made and attached with those permissions!
Just run the test suite =)
If you'd like to try it out yourself, spin up the LCN with docker (`cd services/learn-card-network && docker compose up`)
Then:
```ts
let a = await initLearnCard({
seed: "a",
network: "http://localhost:4000/trpc",
cloud: { …
```
> [LC-634] Default Permissions When Claiming

- .changeset/clever-ducks-vanish.md
- packages/learn-card-network/brain-client/src/index.ts
- packages/learn-card-network/cloud-client/src/index.ts
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- packages/plugins/learn-cloud/src/plugin.ts
- tests/e2e/tests/init.spec.ts
While I was working on the family stuff, I realized that we are unnecessarily `await`ing multiple
different tRPC requests to LearnCloud and LCN when calling `initLearnCard`
Removes the `await` from the relevant calls
For almost everything I was able to move the `await` to be in front of any method that actually needed
these things, with the only exception being the call to `learnCard.id.did()` after you've gotten your LCN account
If it's totally necessary, you can forcibly make sure that is properly waited for by calling `await learnCard.invoke.getProfile`
prior to calling it, but I think that in every current case, there is a reasonable delay between when
you would initialize the wallet vs getting the did.
This situation _does_ bother me though, and there's a couple of more robust fixes: …
> Improve Initialization Speed

- .changeset/four-papayas-drum.md
- packages/learn-card-init/src/initializers/didWebLearnCardFromSeed.ts
- packages/learn-card-init/src/initializers/didWebNetworkLearnCardFromSeed.ts
- packages/learn-card-init/src/initializers/learnCardFromSeed.ts
- packages/learn-card-init/src/initializers/networkLearnCardFromSeed.ts
- packages/learn-card-init/src/types/LearnCard.ts
- packages/plugins/learn-cloud/src/plugin.ts
When switching to a Child Account, it's linking the child's LearnCloud with the parent, which we don't want!
Allow not automatically associating dids in the LearnCloud plugin via init flag
Yet another long name init config variable. This could have possibly been done in a different way,
but I like this approach
> Don't Always Associate Dids in LearnCloud

- .changeset/shiny-hounds-smell.md
- packages/learn-card-types/src/lcn.ts
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
- services/learn-card-network/brain-service/src/accesslayer/claim-hook/create.ts
- services/learn-card-network/brain-service/src/accesslayer/claim-hook/delete.ts
- services/learn-card-network/brain-service/src/accesslayer/claim-hook/read.ts
- services/learn-card-network/brain-service/src/accesslayer/claim-hook/relationships/create.ts
- services/learn-card-network/brain-service/src/accesslayer/claim-hook/relationships/read.ts
- services/learn-card-network/brain-service/src/accesslayer/role/create.ts
- services/learn-card-network/brain-service/src/app.ts
- services/learn-card-network/brain-service/src/helpers/claim-hooks.helpers.ts
- services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
- services/learn-card-network/brain-service/src/models/ClaimHook.ts
- services/learn-card-network/brain-service/src/models/index.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/src/routes/claim-hooks.ts
- services/learn-card-network/brain-service/src/types/claim-hook.ts
- services/learn-card-network/brain-service/test/claim-hooks.spec.ts
- tests/e2e/tests/claim-hooks.spec.ts
[LC-740] Leader Merit Badge Permissions Bug?
In order to facilitate proper permissions for scouts, we need a way to update someone's permissions for a
different boost up the parent tree when claiming a child boost
Adds Claim Hooks that allow you to update permissions for an arbitrary boost when claiming a boost
- New node: `ClaimHook`
- New relationships: `hookFor`, `target`, `roleToGrant`
- `(c: ClaimHook)-[:HOOK_FOR]->(b:Boost)`
- `(c: ClaimHook)-[:TARGET]->(b:Boost)`
- `(c: ClaimHook)-[:ROLE_TO_GRANT]->(r:Role)`
- New router: `claimHook`
- New routes `createClaimHook`, `getClaimHooksForBoost`, `deleteClaimHook`
- `createClaimHook(input: { hook: ClaimHook }) => string`
- Creates a claim hook attached to a specified boost, returning the URI of the new claim hook
- …
> [LC-740] Claim Hooks

- .changeset/purple-beers-retire.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
**[CHECKOUT THIS BRANCH](https://github.com/WeLibraryOS/learncardapp/pull/680)**
[LC-815](https://welibrary.atlassian.net/browse/LC-815)
Currently, when a child is added to a family, they receive a credential that is immediately claimed. However, a notification is also sent when the credential is issued. If the user views this notification and clicks "Claim," they end up with duplicate credentials.
This PR resolves the issue by suppressing the notification when a child is added to a family, preventing unnecessary duplicate claims.
1. updates `sendBoost` route, adds `options` to the `input` parameter
```javascript
.input(
z.object({
...
options: z
.object({
skipNotification: z.boolean().default(false).optional(),
}).optional(),
})
)
```
1. Run LearnCardApp with docker
2. Connect to …
> LC-815 - Skip Notification 

- .changeset/brave-gorillas-count.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
- services/learn-card-network/brain-service/src/routes/credentials.ts
[TEST WITH THIS PR](https://github.com/WeLibraryOS/learncardapp/pull/680)
[LC-786](https://welibrary.atlassian.net/browse/LC-786)
Currently, when a child is added to a family, they receive a credential that is immediately claimed. As a result, the parent receives a notification stating that the child has accepted the credential. However, the notification is missing the child's display name, resulting in incomplete messaging: " has claimed credential".
This PR introduces an optional parameter to suppress the notification when the credential is automatically accepted, preventing incomplete notifications from being sent.
```javascript 
acceptCredential: (
uri: string,
options?: {
skipNotification?: boolean;
}
) => Promise<boolean>;
```
> LC-786 - Suppress Notification on AcceptCredential

- .changeset/twelve-buses-cover.md
- .gitignore
- packages/learn-card-types/src/lcn.ts
- services/learn-card-network/brain-service/src/helpers/claim-hooks.helpers.ts
- services/learn-card-network/brain-service/src/routes/claim-hooks.ts
- services/learn-card-network/brain-service/test/claim-hooks.spec.ts
- tests/e2e/tests/claim-hooks.spec.ts
[LC-796] On full family page: I don't see myself as a member after joining as a parent
We need a way to automatically add someone as a boost admin when they claim a boost
Adds the `ADD_ADMIN` hook
(Breakdown written by Aider with Deepseek R1 😄)
Add ADD_ADMIN Claim Hook type that automatically grants admin privileges when claiming a boost. This enables:
- Automatic admin role assignment for target boosts when claiming a source boost
- Requires admin permissions on both source and target boosts to create hook
- Cascading deletion when either boost is removed
- Validation of admin permissions hierarchy during hook creation
None!
Run both the unit tests in the brain service and the end to end tests!
I wrote a unit test for making sure you are an admin of both the target and claim boost, as …
> [LC-796] ADD_ADMIN Claim Hook

- .changeset/clean-clouds-push.md
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
- tests/e2e/tests/boosts.spec.ts
This PR enables 
1. deleting boosts that are already live
2. prevents deleting boosts with children
>
> LC-823 - Allow deleting live boosts + Prevent deleting boosts with children

- .changeset/clean-steaks-float.md
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/src/routes/contracts.ts
- services/learn-card-network/brain-service/src/routes/credentials.ts
- services/learn-card-network/brain-service/src/routes/presentations.ts
- services/learn-card-network/brain-service/src/routes/profiles.ts
[LC-899](https://welibrary.atlassian.net/browse/LC-899)
This PR updates our OpenAPI HTTP endpoints to accept uri values as query parameters instead of path parameters. The goal is to ensure robust and reliable handling of resource identifiers (URIs) that may contain special characters, such as /, :, or others, which can cause issues with path-based routing and URL encoding/decoding. This change improves interoperability, reduces 404 errors, and aligns our API with best practices for handling complex identifiers.
For example, here is a request to get a ConsentFlow contract using HTTP. It returns a 404, even though this contract URI does exist (and returns correctly using tRPC):
Path parameters cannot safely contain slashes (/), colons (:), or other reserved URL characters—even when …
> 🚑🚨 [LC-899] Fix: URIs in HTTP routes

- .changeset/large-hairs-tap.md
- .changeset/smart-islands-double.md
- .changeset/wicked-crabs-compete.md
- packages/learn-card-types/src/lcn.ts
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- pnpm-lock.yaml
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/manageAutoboosts.ts
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/read.ts
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
- services/learn-card-network/brain-service/src/helpers/consentflow.helpers.ts
- services/learn-card-network/brain-service/src/helpers/did.helpers.ts
- services/learn-card-network/brain-service/src/models/ConsentFlowContract.ts
- services/learn-card-network/brain-service/src/models/ConsentFlowTerms.ts
- services/learn-card-network/brain-service/src/routes/contracts.ts
- services/learn-card-network/brain-service/test/consentflow.spec.ts
- services/learn-card-network/learn-cloud-service/src/accesslayer/credential-record/update.ts
- services/learn-card-network/learn-cloud-service/src/routes/indexPlane.ts
- tests/e2e/tests/consentflow.spec.ts
- tests/e2e/tsconfig.json
[LC-894] Supporting creating a ConsentFlow where multiple accounts have ability to use contract to write credentials
Supporting creating a ConsentFlow where multiple accounts have ability to use contract to write credentials
This PR adds multiple writers to a consent flow contract.
- Added `resolveAndValidateDeniedWriters` helper to `src/helpers/consentflow.helpers.ts`.
- Refactored `updateConsentedContractTerms` route to consume the helper.
- Hardened error-handling & validation messages.
- Fixed type mismatches and ESLint formatting across touched files.
- Updates terms to include `deniedWriters` field.
- Updates `contract` type to include `deniedWriters` field.
- Moved inline validation logic into a shared helper for maintainability.  
- Adjusted some TRPC error codes for consistency …
> [LC-894] Multiple Contract Issuers

- .changeset/rare-clubs-wash.md
- services/learn-card-network/brain-service/src/accesslayer/credential/relationships/read.ts
- services/learn-card-network/brain-service/src/accesslayer/presentation/relationships/read.ts
- services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
- services/learn-card-network/brain-service/src/helpers/presentation.helpers.ts
- services/learn-card-network/brain-service/test/credentials.spec.ts
- services/learn-card-network/brain-service/test/presentations.spec.ts
- tests/e2e/tests/credentials.spec.ts
- tests/e2e/tests/presentations.spec.ts
[LC-1003] Do not allow accepting a credential twice
Right now, if someone sends you a credential, you can accept it multiple times. This is a bug.
Fixes that so that you can only accept it once.
- Run the unit tests (`cd services/learn-card-network/brain-service && pnpm test`)
- Run the E2E tests (`cd tests/e2e && pnpm test:e2e`)
Added both unit tests and E2E tests =)
[LC-1003]: https://welibrary.atlassian.net/browse/LC-1003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
The purpose and impact of these changes is to prevent users from accepting the same credential or presentation multiple times.
Main changes:
- Added checks to verify if a credential/presentation has already been received before accepting
- Implemented new functions to query if …
> [LC-1003] Do not Allow Accepting a Credential/Presentation More Than Once

- .changeset/violet-deer-brush.md
- pnpm-lock.yaml
- services/learn-card-network/brain-service/lambda.ts
- services/learn-card-network/brain-service/package.json
- services/learn-card-network/brain-service/src/helpers/shim.ts
- services/learn-card-network/brain-service/src/routes/index.ts
- services/learn-card-network/brain-service/src/routes/profiles.ts
- services/learn-card-network/learn-cloud-service/src/routes/index.ts
[LC-1070] LearnCard Network Brain Service Lambda not passing headers on POST requests to OpenAPI routes
Our OpenAPI routes are broken =(
Correctly passes through the headers object and correctly interprets it
I needed to add a `http.createServer` call in the lambda and then correctly handle the headers object being a `Map` (kind of weird though, because it was actually a `HeadersList` when I logged it and so `instanceof Map` didn't work even though it acts exactly like a Map)
Run it locally with serverless:
```
docker run neo4j
docker run redis
cd services/learn-card-network/brain-service && pnpm start-p-4000
```
In `src/routes/index` there is a `createContext` function that gets a `authHeader` string. Add a console
log that logs this out, then run the below command:
```
curl -X POST …
```
> [LC-1070] OpenAPI Headers Fix

- .changeset/silly-aliens-tease.md
- packages/learn-card-types/src/lcn.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
- services/learn-card-network/brain-service/src/models/Boost.ts
- tests/e2e/tests/boosts.spec.ts
[LC-1086] Add "allowAnyoneToCreateChildren" flag to Boost model to bypass role-based child-creation checks
Introduce a new Boost-level flag `allowAnyoneToCreateChildren` that, when set, bypasses role-based permission checks and lets **any** profile create child boosts. This enables more open, community-driven boost hierarchies without manual role assignment.
* Added optional `allowAnyoneToCreateChildren` boolean to Boost schema & shared types
* Permission gate `canProfileCreateChildBoost` now short-circuits when flag is `true`
* Updated create/update flows, unit tests, and E2E test (`tests/e2e/tests/boosts.spec.ts`)
* Changesets updated (`silly-aliens-tease`) to publish patches to affected packages
Run the unit tests and the E2E tests =)
[LC-1086]: …
> [LC-1086] Anyone Can Make Children

- .changeset/moody-yaks-check.md
- packages/learn-card-cli/package.json
- packages/learn-card-cli/src/index.tsx
- pnpm-lock.yaml
Make it easier for people to create / register signing authorities, using CLI
```
// Must create profile before creating / registering signing authorities
// Await learnCard.invoke.createProfile({ profileId, displayName, isServiceProfile: true })
// Retrieve managed signing authorities from LearnCard App
await learnCard.invoke.getSigningAuthorities()
// Create a signing authority with name “lca-sa” if it doesn’t exist in LearnCard App
const managedAuthority = await learnCard.invoke.createSigningAuthority(‘lca-sa’)
// Register signing authority with LearnCard Network, to authorize it to send credentials over the network to your managed “lca-sa” (it will set as primary if this is the first one)
await learnCard.invoke.registerSigningAuthority(managedAuthority.endpoint, managedAuthority.name, …
```
> Feat: Add Simple Signing Plugin to CLI

- .changeset/chilly-swans-teach.md
- services/learn-card-network/brain-service/src/accesslayer/boost/create.ts
[LC-1121] Open ai tutor just loads indefinitely or for a really long time) when starting a new session.
When starting AI tutor it takes forever!
I _think_ this is happening because of a Neo4j Deadlock that can happen when creating a child boost.
We have this `Promise.all` call that does _two_ Neo4j queries at the same time, which could lead to a deadlock.
Moves those two calls to happen all in a single Neo4j Query! This actually speeds up the whole thing and removes the deadlock issue.
None =) This is just better.
Just run the test suite! If this broke anything, tests would catch it =)
[LC-1121]: https://welibrary.atlassian.net/browse/LC-1121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Purpose: Fix Neo4j deadlock in boost creation by …
> [LC-1121] Long Loading Times/Neo4j Deadlock

- .changeset/bumpy-suits-fetch.md
- .changeset/hip-pears-dig.md
- packages/learn-card-types/src/lcn.ts
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
- services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
- services/learn-card-network/brain-service/test/consentflow.spec.ts
- tests/e2e/package.json
- tests/e2e/tests/consentflow.spec.ts
- tests/e2e/tests/helpers/contract.helpers.ts
[LC-1173] consentflow - get with Chris
Adds a UI hint to enable parts of a contract without requiring them and fixes a security issue
Previously you could issue autoboosts even if the user didn't give permission for that!
Run the brain service tests and the E2E tests =)
[LC-1173]: https://welibrary.atlassian.net/browse/LC-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Purpose: Add defaultEnabled UI hint flags to consent flow contracts and implement permission checks for autoboost issuance.
Main changes:
- Extended ConsentFlowContract schema with defaultEnabled flags for read/write permissions
- Added permission validation to prevent autoboost issuance without explicit write permissions
- Added tests to verify defaultEnabled flags and …
> [LC-1173] defaultEnabled and autoboost permissions

- .changeset/nice-ligers-wink.md
- .github/actions/setup/action.yml
- .github/workflows/deploy.yml
- .github/workflows/docker-release.yml
- .github/workflows/maids.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- services/learn-card-network/brain-service/project.json
- services/learn-card-network/brain-service/serverless.yml
- services/learn-card-network/brain-service/src/constants/auth-grant.ts
- services/learn-card-network/learn-cloud-service/project.json
- services/learn-card-network/learn-cloud-service/serverless.yml
- services/learn-card-network/learn-cloud-service/src/constants/xapi.ts
- services/learn-card-network/learn-cloud-service/src/mongo.ts
This PR introduces a more sophisticated and automated deployment strategy to differentiate between staging and production environments. Previously, all pushes to `main` would trigger a deployment.
The goal is to create a seamless CI/CD flow where:
* Standard pushes to the `main` branch automatically deploy to `staging` for continuous integration and testing.
* Merging an official release PR (generated by the `release.yml` workflow) automatically triggers a deployment to our `production` environments.
* Manual deployments to any environment via `workflow_dispatch`.
The `deploy.yml` workflow now automatically deploys to `staging` on every push to `main`. It only deploys to `production` when a commit from our `release.yml` workflow (identified by a `chore(release):` prefix) is merged, …
> ✨ feat: Git Environments + Staging CI/CD

- .changeset/cold-rings-rhyme.md
- packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
- packages/react-learn-card/src/components/CertificateDisplayCard/MediaAttachmentsBox.tsx
This PR puts up a fix for when the name of a pdf file is too long from running off the screen in Media Attachments for a credential. (LC-1248) It also adds a fix when someone's name is too long from getting cut off on the certificate front face.(LC-1254)
https://welibrary.atlassian.net/browse/LC-1248
https://welibrary.atlassian.net/browse/LC-1254
**Before**
**After**
https://github.com/user-attachments/assets/b7038c79-cef2-42ad-b0db-9eed5d7ce1dc
Purpose: Fix UI display issues with certificate names and document metadata to improve readability and prevent text overflow.
Main changes:
- Added text-center class to certificate name display to properly center long names
- Improved document attachment container with min-w-0 to enable text overflow handling
- Fixed background image gradient …
> [LC-1248] & [LC-1254]

- .changeset/shaky-wings-cheer.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
- services/learn-card-network/brain-service/src/routes/boosts.ts
- services/learn-card-network/brain-service/test/boost.countRecipientsWithChildren.spec.ts
- services/learn-card-network/brain-service/test/boosts.spec.ts
- tests/e2e/tests/boosts.spec.ts
[LC-1228] Create countBoostRecipientsWithChildren resolver
- Add counting of unique boost recipients across a boost’s descendants.
- Expose `boost.getBoostRecipientsWithChildrenCount(...)` and brain-service resolver/route.
- Maintain filtering and traversal parity with recipients-with-children listing.
Add count across child boosts with filters, generation depth, and unaccepted-boosts toggle; unit + e2e tests included.
- Server: `countBoostRecipientsWithChildren` resolver
- `services/learn-card-network/brain-service/src/routes/boosts.ts`
- `services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts`
- Client: `boost.getBoostRecipientsWithChildrenCount`
- `packages/plugins/learn-card-network/src/plugin.ts`
- `packages/plugins/learn-card-network/src/types.ts`
- …
> [LC-1228] countBoostRecipientsWithChildren

- .changeset/tender-bags-unite.md
- packages/learn-card-network/cloud-client/src/index.ts
[LC-1332] Lower maxItems in LearnCloud tRPC client to 50 to avoid AWS Lambda max response payload
If you send too many batch requests to the lambda, AWS actually errors its response!
Limit the amount of requests in a single batch to 50
Add `maxItems: 50` to the LearnCloud tRPC client
This isn't a perfect fix. It could be 50 requests that happen to return a _ton_ of data and still hit that limit (its like 6 MB I think or something like that),
and this also could block say 500 tiny requests that wouldn't hit that limit, but I think it's a fair tradeoff at 50.
You can just run the E2E tests to make sure things still work!
[LC-1332]: https://welibrary.atlassian.net/browse/LC-1332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Purpose: Add maxItems …
> [LC-1332] Stop Hitting Lambda Response Limit with LearnCloud tRPC client

- .changeset/wet-drinks-double.md
- packages/plugins/learn-card-network/src/plugin.ts
- packages/plugins/learn-card-network/src/types.ts
- services/learn-card-network/brain-service/CLAUDE.md
- services/learn-card-network/brain-service/src/cache/invites.ts
- services/learn-card-network/brain-service/src/routes/profiles.ts
- services/learn-card-network/brain-service/test/profiles.spec.ts
- tests/e2e/tests/invites.spec.ts
[LC-1242] Invite to connect not working
Expose enhanced Profile Connection Invite routes in the LearnCard network plugin and add end-to-end tests to validate multi-use, unlimited, expiration, and invalidation behavior from the client perspective. Ensure the project builds and E2E tests pass.
- Expose `generateInvite(challenge?, expiration?, maxUses?)`, `listInvites()`, and `invalidateInvite(challenge)` in the network plugin.
- Align types to return `expiresIn` and accept `maxUses` (0 = unlimited).
- Add E2E tests `tests/e2e/tests/invites.spec.ts` for single-use, multi-use, unlimited, and invalidation flows.
- Improve OpenAPI docs and `CLAUDE.md` for invites.
- `packages/plugins/learn-card-network/src/types.ts`
- Add `listInvites()`, `invalidateInvite(challenge)`.
- Extend `generateInvite` …
> [LC-1242] Invite Updates

- .changeset/bright-plants-wash.md
- .changeset/eight-seals-cross.md
- services/learn-card-network/brain-service/src/dids.ts
- services/learn-card-network/learn-cloud-service/src/dids.ts
- services/learn-card-network/simple-signing-service/src/dids.ts
Existing didkit JWE creation is dependent on `keyAgreement` containing a `publicKeyBase58` field and
will crash if it's not there! Our latest update changed it to use `publicKeyMultibase` instead, causing
existing code to break. New clients will no longer crash though, and so eventually we can just use
use the new one =)
Reverts the `keyAgreement` field to use `publicKeyBase58`
This reverts us using `X25519KeyAgreementKey2020` and puts us back on `X25519KeyAgreementKey2019`.
In the future we'll probably want to just move to 2020.
Run the whole E2E suite, and then while it's running spin up the CLI with _old_ code:
```bash
pnpm dlx @learncard/cli
```
Then, in the CLI, try out some things! Specifically make sure encryption/decryption work:
```js
let test = await initLearnCard({ seed: 'a', …
```
> [Hotfix] KeyAgreement Backwards Compatibility

- .changeset/eleven-apes-explain.md
- services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
If you run the LCA backend services via docker for the purpose of development, you will find that the inapp notifications don't work at all.
Fix notifications not working when running dockerized LCA backend services for local dev
Notifications use the function addNotificationToQueue which is used like everywhere when we want to enqueue a notification. In the addNotificationQueue to function there is a block that looks like this and when running the service locally it early returns if these conditions are met
```
if (
process.env.NODE_ENV === 'test' ||
process.env.IS_OFFLINE ||
!process.env.NOTIFICATIONS_QUEUE_URL
) {
console.log('///EARLY RETURN ADD NOTIFICATION');
return; // Can not use SQS in test environment or locally
}
```
when running locally process.env.IS_OFFLINE is set to true …
> fix: Add local dev fallback for notification queue 

- .changeset/brown-walls-clap.md
- packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
Run this [PR](https://github.com/WeLibraryOS/learncardapp/pull/1040) with it.
This PR fixes the issue of a really long title running off the screen when you view the details for a merit badge.
https://welibrary.atlassian.net/browse/LC-1400
https://github.com/user-attachments/assets/2a09ca95-89db-40e5-bbca-4260f7e92ad2
Purpose: Fix UI issue in MeritBadgeFrontFace component where long badge titles were overflowing container boundaries.
Main changes:
- Added width constraint (w-full) to the title container to ensure proper text wrapping
- Applied w-full to parent container to ensure consistent width management across nested elements
- Added changeset file to document patch version bump for @learncard/react package
<sub>AI-generated content …
> fix: [LC-1400] Fix long title for merit badge from running off screen
